### ISSUE TITLE
Add a toxicology refiller

### ISSUE THREAD

**Issue by vadi2** [svof/svof#10]
Update the forestal refiller to work with toxicology as well.

**Comment by QwindorRousseau** [comment]
They updated the handling of this game side to where you don't have to inpot or put into an alembic anymore so slightly defunct to have a system that does this though I can take a look at it and make it work with the new stuff for refilling vials for large orders

**Comment by QwindorRousseau** [comment]
Yea going to close this due to the changes in game. We already have a refiller that will do tuns but I think a new issue for enchancement to add in the functionality to have it refill to the rift should be opened
