### ISSUE TITLE
SVOF attempts to cure (and believes it cured) Lovers Tarot with RAGE.

### ISSUE THREAD

**Issue by Tsagh** [svof/svof#103]
I was fighting an occultist, and got hit with Lovers Tarot. Since I had configured the system to use RAGE to cure peace-type afflictions the system attempted to use it. It then saw that RAGE was used and assumed that "inlove" was cured. Unfortunately, RAGE doesn't actually cure lovers tarot. There was an awkward moment where the man I loved killed me while my feelings for him would not let me fight back. It was true tragedy.

Fix: No longer use RAGE when afflicted with "inlove" and remove it from the list of afflictions removed upon using the skill.

I'll wait a few days for comments/concerns before branching and putting in a fix. Feel free to assign this to me.

-Spetum

**Comment by keneanung** [comment]
I just tried it and RAGE got rid of the lovers effect for me. See http://pastebin.com/sMJCzwTG

**Comment by Tsagh** [comment]
Alright, I went and tested this again and it worked just like in your log there. In the spar I used RAGE, got the message that I used it and it cured nothing. Then I stood there not curing it. I'll have to try to recreate the situation. There is an issue here, but it seems that I misidentified it. Do you have any ideas as to what would cause something like this to happen?

**Comment by keneanung** [comment]
The only thing that comes to my mind (which doesn't mean it's the only possible reason) is that it was still waiting for rage to go through. Maybe it didn't recognise the failure message?
