### ISSUE TITLE
Minor tattoo inker issues

### ISSUE THREAD

**Issue by keneanung** [svof/svof#104]
The functions `svo.ti_inknext` and `svo.ti_noinks` do not check, whether an inking process was started or not and can be called when svo.ti_inking is not a table.

The function `svo.ti_finishedinking` checks for the table `ti_inking` without the svo prefix. I'm not sure right now whether this makes any difference (but at least it's inconsistent with the other checks).

If the user does not have the skill to ink the tattoo, `svo.ti_noinks` gets called and the user gets the message that they don't have the necessary inks...

**Comment by keneanung** [comment]
Another improvement: you can just do 'ink tattoo on me' instead of specifying 'on head of me' 'on left leg of me' etc for tattooing. No need to search for open spots anymore.

**Comment by QwindorRousseau** [comment]
Closing due to the following: I made some updates with #394 and took out the OUTR portion of the script as it is not needed anymore and the game auto takes them from the rift when you start the inking process.
