### ISSUE TITLE
Missing message in trigger for Weaponmastery: Devastate

### ISSUE THREAD

**Issue by Tsagh** [svof/svof#105]
The current trigger for "crippling blow" style devastate messages is only set up to work for bastard swords, not hammers.

Missing trigger line looks like this example:
Spetum aims a devastating blow with a Hellforge Hammer at your already injured legs.

regex:
^\w+ aims a devastating blow with .+ at your already injured legs\\.$

It should be added to the trigger: svo/weaponmastery/two-handed/Devastate legs cripple
It's a quick fix I'm happy to do if you assign it.

-Spetum

**Comment by Tsagh** [comment]
Later today, I'll do some testing to ensure that I have all of the lines right, and they are matching the correct functions. There may be other improvements needed than adding the one line.

**Comment by keneanung** [comment]
Feel free to have a go on that. Seems like only members of the organization can be assigned to issues.

**Comment by Tsagh** [comment]
Made a branch on my local machine and tried to sync it, but I didn't have permission.

**Comment by keneanung** [comment]
You'll want to create a fork (use the button on the top right). After that, you can add another remote with `git remote add fork https://github.com/Tsagh/svof.git`.

Now you can push your branch to your fork with `git push fork` and create a pull request from the GitHub page of your fork (see https://help.github.com/articles/creating-a-pull-request/).

Only Vadi, me and a bot can push to this repo at the moment. That way we can enforce a pee review through PRs.

**Comment by vadi2** [comment]
pls don't send me urinal samples

**Comment by keneanung** [comment]
Edited, sorry :sob:
