### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by seriley** [svof/svof#108]
I get an unknown svof error at the same point when fighting the spiders in the Istar Jungle. It only occurs (when it does) when fighting the spiders.

Here are some lines as they appear on screen:

As you point an elemental staff at a monstrous gamling spider, a scintilla of bright, burning light 
shoots out, striking him with focused elemental power.
3392h, 3214m, 16955e, 14471w cxkdb-
You may eat another bit of irid moss or potash. (5.946s)
3392h, 3214m, 16955e, 14471w cxkdb-
A monstrous gamling spider sticks you with the end of one sharply hooked leg, pinning you to the 
ground mercilessly.
2798h, 3289m, 16955e, 14477w cxkdb[pr]-
You are too stunned to be able to do anything.
2798h, 3289m, 16955e, 14477w cxkdb[stun pr]-
(e!)
You are no longer stunned. (0.352s)
2798h, 3289m, 16955e, 14477w cxkdb[pr]-
You can use Windlash again.
2798h, 3289m, 16955e, 14477w cxkdb[pr]- (4.372s)
You take a drink from a purple heartwood vial.
The elixir heals and soothes you.
3427h, 3289m, 16955e, 14477w cxkdb[pr]-

I am using the default prompt that svof sets when installed for a magi

**Comment by seriley** [comment]
When it occurs, it always occurs with the following three lines:

You are too stunned to be able to do anything.
2798h, 3289m, 16955e, 14477w cxkdb[stun pr]-
(e!)

**Comment by keneanung** [comment]
You should be able to click on the (e!) and a more informative error message should be shown. Can you try that and post the message?

**Comment by jgh713** [comment]
Tried my best to reproduce this issue a ways back. @seriley if you have any custom prompt tags, any instance in which those don't return a proper value or error out will cause an (e!) message like this.

Close this for now and reopen if it pops up again, perhaps with a bit more context available?

**Comment by seriley** [comment]
Closing issue. I will check if it still occurs next time I'm up there
