### ISSUE TITLE
gmcp Race related error message on login

### ISSUE THREAD

**Issue by keneanung** [svof/svof#126]
> Sent By: Seldin On 1/08/7:55
> // Hi. I recently (finally) upgraded to Svof from an older Svo version. When I log in I often see this message: "...\mudlet\profiles\Seldin - Achaea SVO/Serpent svo/svo:18583: attempt to index field > 'race' (a nil value)" - would you have any idea how I might fix this? Thanks.
> // Hasn't broken anything that I can see. Happens immediately on log-in. Happened 3 times in a row on my login this time.

This seems to be happening only to certain people.

**Comment by CUltiris** [comment]
Deana & Raoh have had this issue, also both Serpents.

**Comment by EldFitheach** [comment]
Well, that's in the function that checks for dragonform on receiving gmcp.Char.Status, indicating that somehow gmcp.Char.Status.race isn't being populated. It might help if someone who's having the problem could check the values in that table when they get the error.

**Comment by keneanung** [comment]
I tried to do that with Raoh when I helped him fixing things, but I didn't have the time to closely debug it.

Any takers for a closer look? I'd be also happy if someone took the time and analyse this better without developing a fix.

**Comment by gjv6662** [comment]
Alright, so, I went ahead and searched for gmcp.Char.Status.race and it didn't come up, unless it's somewhere that it won't come up.  I'd be willing to help in any way that I can.  This is Deana, btw.

**Comment by EldFitheach** [comment]
Probably the easiest way to check the values would be to create a script to display the gmcp.Char.Status table whenever the gmcp.Char.Status event is raised. The following should work:

  function testcharstatus()
      display(gmcp.Char.Status)
  end
  registerAnonymousEventHandler("gmcp.Char.Status","testcharstatus")

Whenever that event is raised, you should see something like:
  {
    name="Yourname",
    class="Yourclass",
    race="Yourrace",
    ...,
  }
If you can do that and copy/paste a log of logging in and the first couple prompts afterward, it might offer some clues. All those printouts will be rather spammy, so once you've got a log, just delete or disable the script.

**Comment by EldFitheach** [comment]
Ok, based on a log from Deana, it looks like for some reason she's getting gmcp.Char.Status event on login with just the gold field, so the function that checks for dragonform doesn't find the race field when it looks. No real problem beyond the annoying error request. https://github.com/svof/svof/pull/137 is a quick fix.
