### ISSUE TITLE
Serverside breathing not stopped when dragonforming

### ISSUE THREAD

**Issue by keneanung** [svof/svof#131]
> Sent By: Kard On 1/21/12:21
> I was using "dragonform black" and svof didn't seem to pause breathing while the system was paused. I have serverside curing on. https://ada-young.appspot.com/pastebin/e9278e1c.

**Comment by keneanung** [comment]
> Sent By: Keneanung On 1/21/16:57
>(To Kard): The log didn't show too much (for example no start of dragonforming) and I am no dragon myself so I can't confirm and this is the first report of the form. But I created an issue (https://github.com/svof/svof/issues/131) so I can look at it later. Jus to confirm: the (p) markers appear when you are dragonforming?

**Comment by keneanung** [comment]
> Sent By: Kard On 1/21/17:17
> That's correct. On dragonform svo pauses until interrupted or complete. I had keepup breath on and it appears (maybe due to an issue with serverside curing and svo) that when I got balance back it tried to hold breath instead of noticing I'm paused.

**Comment by keneanung** [comment]
> Sent By: Keneanung On 1/21/17:24
> (To Kard): And you told svo that you are using serverside (tn ss) right?

**Comment by vadi2** [comment]
Yeah the log doesn't show the start of dragonforming, upon which Svof should've sent the command to serverside to pause serverside.

**Comment by keneanung** [comment]
> Sent By: Kard On 1/21/20:33
> Correct. Serverside has been on for a while.

**Comment by jgh713** [comment]
This seems to be fixed.

**Comment by keneanung** [comment]
Will try to poke Kard about this.

**Comment by jgh713** [comment]
Dragonforming only pauses svo local, not serverside. Needs to be fixed, should be relatively simple.
