### ISSUE TITLE
Disable peopletracker by default

### ISSUE THREAD

**Issue by keneanung** [svof/svof#133]
The svof peopletracker can lock down slow computers. Disabling it by default and asking a question on vinstall with a visible warning could help with that.

This will not help with existing installations though.

**Comment by keneanung** [comment]
Another idea by @vadi2:
> I think a better solution would be to time how long it takes to show an alertness message, and if it's too much, auto-disable with a message & link on how to enable.
>
> That way you won't be asking people at installation time about something they've actually got no idea about and it'll not be a bother for those who run slow PC's.

**Comment by jgh713** [comment]
Not 100% sure why this is here, given that this is almost entirely mudlet mapper? And I think it was addressed with Qwindor's alertness change.

The only things I can see that the people tracker actually does is the building of a qwho summary and the tracking of a watchfor list.

**Comment by jgh713** [comment]
Closing, as not a svo issue and already resolved.
