### ISSUE TITLE
Add another nausea symptom

### ISSUE THREAD

**Issue by keneanung** [svof/svof#134]
`Your superior constitution allows your body to fight off the negative affects of your nausea.` This nausea symptom is currently missing. Not sure if it is `affects` or `effects`.

**Comment by johndahlstrom** [comment]
I believe this is when the Constitution defence (found in Kaido) is up and blocks the application of nausea.

**Comment by keneanung** [comment]
Yes. The only question is, wether it is `affects` as in the bug report I got or `effects`.

**Comment by EldFitheach** [comment]
It's "affects", but I just put in a typo to change it to "effects" as it should be, so it might be changed soon.

**Comment by jgh713** [comment]
Update, still affects, not effects. Best to add both lines, for when they fix it?

**Comment by keneanung** [comment]
Might be a reasonable way to handle this
