### ISSUE TITLE
Missing Dual Blunt Triggers and Affliction

### ISSUE THREAD

**Issue by Kellonius** [svof/svof#145]
This trigger needs to be added for when Lagua fires on dual blunt attacks:

^The right side of your body loses all feeling as the weapon of \w+ discharges energy into you\.$

This should set svo.valid.simplenumbedrightarm()

The trigger named "Expend head" needs to have this added:

svo.valid.simpleconfusion()

**Comment by jgh713** [comment]
#209 should fix
