### ISSUE TITLE
SVOF - Autoreject Lust - Not rejecting anyone

### ISSUE THREAD

**Issue by rangorC** [svof/svof#147]
It seems SVOF is having some difficulties with autorejecting on lust. The affliction tends to register, but no rejecting is done. 

5 Credit bounty when fixed! Will try to add logs later.

**Comment by jgh713** [comment]
With serverside on, svo doesn't reject at all. Works fine not using serverside.

Manually rejecting with serverside on doesn't recognize you losing the affliction, nor does checking your allies and seeing that you don't have that.

Also, if you've rejected someone and svo doesn't recognize it, it'll spam reject, and never realize that "Why would you reject <person>?" means they're not lusted.

**Comment by jgh713** [comment]
@rangorC 'vshow server' and tick lovers. It's ticked by default but if you remove it it doesn't work. @keneanung perhaps this should be removed from the list altogether, since serverside doesn't handle it?

**Comment by keneanung** [comment]
Might be a good idea.

**Comment by QwindorRousseau** [comment]
Fixed with #384
