### ISSUE TITLE
Add hoisting whitelist/blacklist

### ISSUE THREAD

**Issue by keneanung** [svof/svof#149]
Similar to the lustlist, it might be useful to have a black and/or whitelist for hoisting.

**Comment by vadi2** [comment]
Adding 25 bounty credits to this.

**Comment by Ditsypop** [comment]
Would it be okay to literally do this in the same way as the lustlist? Similar config options etc? I'll take a go at it.

**Comment by keneanung** [comment]
@Ditsypop that'd be the way I'd go as well

**Comment by keneanung** [comment]
Also removed the `up for grabs` label to reserve it for you :)

**Comment by Ditsypop** [comment]
Thanks in the unlikely event I have irreconcilable difficulties doing it I'll keep you posted

**Comment by keneanung** [comment]
@Ditsypop any updates on this?

**Comment by Ditsypop** [comment]
I've been mia for a bit im working on a good bit of RL stuff and being at doctors pretty often idk if I'll be able to work on anything for a while.

**Comment by keneanung** [comment]
I see. I hope you get better soon! I'll be re-adding the label again, but you can still work on it, of course. Just let me know when I should reserve it for you again :)
