### ISSUE TITLE
Missing lemming passive line

### ISSUE THREAD

**Issue by mattnorr** [svof/svof#150]
Sentinel's WOODLORE entity 'Lemming' passively afflicts with confusion, which svof does not have the line for.:
The lemming races around you and between your legs, confusing you with its eratic movement.
exact match ^
body:
svo.valid.simpleconfusion()

**Comment by keneanung** [comment]
While somebody looks at lemming, here's another one 8reported by Deladan):
> ^A small brown lemming rips apart your (.+) with its claws.$

Should call `svo.valid.defstrip(matches[2])`

**Comment by Ditsypop** [comment]
Went ahead and threw up a commit for this, doing 1 more thing then will do PR

Also @keneanung the trigger you referenced was already there when I looked.

**Comment by keneanung** [comment]
I'd prefer single PRs for every issue, to be honest. Easier to track for me.

**Comment by Ditsypop** [comment]
You got it boss. Filed.

**Comment by keneanung** [comment]
About the trigger being already there: Maybe the message changed slightly? Can you test whether the defstrip is recognized?

**Comment by Ditsypop** [comment]
taking a closer look and testing it out a few times to see what's up.

**Comment by Ditsypop** [comment]
Updated!
