### ISSUE TITLE
Consider uncommenting Vivisect Restore scenario

### ISSUE THREAD

**Issue by keneanung** [svof/svof#152]
Reported by Aerek:
Currently, it's in the code but commented out. I'm not sure about the reasons for this.

**Comment by vadi2** [comment]
It's gameable, people can then force a restore long enough to behead you.
Need to work with a vivi expert on this.

**Comment by Esync7** [comment]
Restore balance was adjusted a while back. Unless you have confusion, an Infernal shouldn't be mathematically able to Behead you. Maybe an Apostate, but you'd have to be locked already.

Either way, you can always disable it via vconfig2 or script enabling/disabling via API, (Which I do) so why does it need to be commented out entirely? It's difficult/dangerous to send newbs/neophytes mucking around in Svo's code to fix this once they do face Vivisect for the first time.

**Comment by vadi2** [comment]
It should've never been turned on or be visible before, it was doing more
harm than good (and misleading people into helping).

**Comment by Esync7** [comment]
Err. All right. We'll have to respectfully disagree on that. **_Some_** Vivisect curing is better than **_no_** Vivisect curing. Right now, everyone using Svo will die to a 2-leg Vivisect, every time. Keeping that scenario commented out is handing easy Vivisects to any DSL Infernal that exists.

I just tested it, there's nuance on the topic. It looks like damaged legs are counting toward Restore at the reduced rate (which is intended) but arms are counting at full rate. I've bugged it, seems against the intended balance, but in the meantime:
- 2x damaged leg + 2x crippled arm Restore is clocking a consistent 10s EQ. (No Diadem) 
- One each damaged arm/leg + crippled arm/leg is taking the full 12.5s EQ. (No Diadem) 
- Behead is clocking consistently 10.5 seconds, and the Infernal has to recover balance (1.9 sec on DSL) before starting it. (12.4s total)
This means that if you Restore to stop Vivisect on a leg/leg setup, (the standard setup) you will regain EQ and can stand 2.4 seconds before Behead completes. If the Infernal can trick you into restoring with damaged arm/leg + crippled arm/leg, then he has a -chance- to Behead you if he reacts perfectly, but several classes still have options to prevent this. (like Arc) If you have a Diadem or are Quick-Witted, then you'll recover EQ before Behead finishes in all cases, and can stop it no matter your class.

Can Vivisect Restore be abused? Yes. So can a lot of other curing options. But dying to Behead **_some_** of the time is better than dying to Vivisect **_all_** of the time. Can disable it by default if you like, but this is a legitimate option that I've used to stop Vivisect (including Behead) for years, and it should be there. It's certainly no more harmful that the any-crippled-limb-while-prone option, which is a terrible idea.

**Comment by CUltiris** [comment]
I agree 100% with Esync7 on this one.  I died immediately and repeatedly with no apparent way to beat a vivi using SVO until I un-commented this scenario.  Having the restore scenario available forces other methods of play.  If it's not behead then it's repeated disembowels.

**Comment by keneanung** [comment]
More discussion about this: http://forums.achaea.com/discussion/comment/316534/#Comment_316534

The overall tenor seems to be that this scenario should be added again
