### ISSUE TITLE
Alchemist affliction tracking is a mess

### ISSUE THREAD

**Issue by keneanung** [svof/svof#153]
reported by Aerek:

```
- Still believes bonus tempers apply when having afflictions of that temper. This leads to wildly inaccurate temper counts.
    - In reality, bonus tempers only apply when targeted humour is at 6, and only if you have affs from 2 other humours' affliction pools. (Jumping from 6 to 8, which is max)
- Does not recognise that consecutive ginger eats cure more than 1 temper at a time. 1st eat cures 1, 2nd eat cures 2, 3rd cures 3, etc.
    - However, this only occurs while the Alchemist is not in the room. (Can't make it easy)
    - This bonus applies only to one humour at a time. 5th eat can cure 5 tempers, but if that eat cures Sang 3, will cure only those 3 tempers, not the tempers of any other humours.
- Sometimes does not remove Vitrification/Corruption when they end:
    - "The glass shards embedded in your skin revert to flesh." (Vitrification off)
    - "The corruption of your humours fades." (Corruption off)
```

**Comment by jgh713** [comment]
The last portion should be addressed with #209 

I'm not sure of a decent way to address the second one.

**Comment by QwindorRousseau** [comment]
@svof/developers we need to verify if this is still an issue with serverside turned off but we also know that the non serverside portion of the system is a mess and needs a ton of cleanup and fixes as it is.

**Comment by DazedxJoker** [comment]
Eating consecutive ginger/antimony doens't appear to remove more than one temper at a time. So that part is irrelevant. (Unless it is broken because I'm also an Alchemist)

**Comment by DazedxJoker** [comment]
After some testing, 
if humour level = 5 and you have at least 1 wrackable affliction the temper = +2

Fortunately, there is a line that informs you that the humour level when up +2 instead of +1

![image](https://user-images.githubusercontent.com/14912622/61668301-4f845080-acaa-11e9-8335-efafc6ed42c7.png)

"A wave of nausea washes over you." means you got a bonus temper

**Comment by DazedxJoker** [comment]
> Eating consecutive ginger/antimony doens't appear to remove more than one temper at a time. So that part is irrelevant. (Unless it is broken because I'm also an Alchemist)

Apparently, it isn't simple consecutive eats, you have to be eating it on bal almost to start the stacking

**Comment by DazedxJoker** [comment]
Going to go ahead an close on approval of #447, the second part seem unnecessarily difficult to implement.
