### ISSUE TITLE
SvoF tries to def Dragonbreath while graced

### ISSUE THREAD

**Issue by keneanung** [svof/svof#154]
Reported by Aerek

**Comment by vadi2** [comment]
Soulcage is another you can't do graced, i think.. Grace tracking needs to
be implemented for this.

**Comment by keneanung** [comment]
Now that you mention it, Kai trance might also fall into this category...

**Comment by jgh713** [comment]
Phase applies now, as well.

**Comment by QwindorRousseau** [comment]
Going to close and reopen for adding grace check. Will have to see if we can track it via GMCP or not.
