### ISSUE TITLE
2 handed lethargy issues

### ISSUE THREAD

**Issue by keneanung** [svof/svof#156]
reported by Aerek

> SvoF thinks the recurring lethargy from arm fractures is A) an illusion or B) means we have hypochondria. Ignoring hypochondria also appears to ignore lethargy. It's really a problem vs 2H.

**Comment by jgh713** [comment]
Should also be addressed (mostly) with #209

**Comment by keneanung** [comment]
Have you checked the behavior after the GMCP changes? If not, I'd leave this open until we could test this after the release.

**Comment by jgh713** [comment]
This was fixed with gmcp implementation.
