### ISSUE TITLE
Add blademaster alleviate

### ISSUE THREAD

**Issue by keneanung** [svof/svof#161]
reported by Aerek

> Will not use Alleviate to cure locks when off Tree balance and not paralysed. (Paralysis prevents Alleviate)
> - No curing scenarios for Alleviate.

**Comment by QwindorRousseau** [comment]
I think the general consensus was that if a class healing skill used balance or equilibrium then we would not add it to the system. If there is enough of a gripe after release of in-client we can add it in and will place a nice big warning on those skills about it consuming balance to use.
