### ISSUE TITLE
Bloodleech sensitivity stripping deaf not recognized

### ISSUE THREAD

**Issue by keneanung** [svof/svof#163]
Bug report by Cooper:
> When you are deaf and bloodleech afflicts you with sensitivity, it says:
> A bloodleech leaps at you, clamping with teeth onto exposed flesh and secreting some foul toxin into your bloodstream. You stumble as you are afflicted with sensitivity.Your hearing is suddenly restored.
> Svof still thinks you got sensitivity, even though deafness protected you from that and it only stripped deafness.

**Comment by keneanung** [comment]
> Sent By: Hirst On 5/25/7:47
> [...]After looking at the trig, a simple fix is to change the line to (svo.valid["proper_"..aff] or svo.valid["simple"..aff])(). That will correctly check for deafness before assuming you have sensitivity.

> Sent By: Hirst On 5/26/5:47
> [...]it is on the Scrag trigger. Should replace the line executed as part of the if statement.

**Comment by jgh713** [comment]
Should be addressed with #209
