### ISSUE TITLE
NDB colours get randomly set to rogues

### ISSUE THREAD

**Issue by keneanung** [svof/svof#166]
For some users, the NDB may randomly reset people or whole organisations to "rogue". See http://forums.achaea.com/discussion/comment/296340/#Comment_296340 and http://forums.achaea.com/discussion/comment/292471/#Comment_292471 following

**Comment by natecox** [comment]
Doesn't seem to affect enemies list, just citizenship.

![image](https://user-images.githubusercontent.com/2782695/27061001-a03140c0-4f95-11e7-8460-b8d3eb376278.png)

**Comment by natecox** [comment]
Further testing: running `citizens;qw;qw` will update the citizens, show them as highlighted once, then immediately show them as rogues. Have to suspect `qw` is starting some process to unset the citizens.

**Comment by natecox** [comment]
scratch that, the second `qw` (and all subsequent) will always show no citizen highlights, but they're still in the database as citizens. `cwho` will properly show them, and then `qw` will work again—once.

**Comment by DanFronius** [comment]
It is a conflict with MXP for as far as I have been able to tell. CONFIG MXP OFF in game works to correct.

**Comment by QwindorRousseau** [comment]
Yes this is due to the MXP. There isn't an obvious solution to this unless they change it on the game end to persist the city colour through MXP as well.
