### ISSUE TITLE
Lines bleed into singleprompt

### ISSUE THREAD

**Issue by keneanung** [svof/svof#168]
Since release v16, some people complain about lines bleeding into singleprompt. See http://forums.achaea.com/discussion/comment/301325/#Comment_301325 and following

**Comment by jgh713** [comment]
I dont think this is still an issue, havent heard any recent complaints. Though, is singleprompt outputting to main, then getting cut and pasted as currentline to the singleprompt window? That seems really unnecessary and is just asking for problems.

**Comment by QwindorRousseau** [comment]
Going to close for now as there is already an issue open for singleprompt problems.
