### ISSUE TITLE
reset.defs on charname removes offline_defences

### ISSUE THREAD

**Issue by macjabeth** [svof/svof#169]
As the title says, it looks like the order in which it is done kinda defeats the purpose of having _offline_defence_ on a _def_dict_.

**signals.systemstart** calls **defload()** which adds the offline defences, then **reset.defs()** is called on **signals.(gmcp)charname**.

Am I wrong to assume this is the case?

**Comment by keneanung** [comment]
I think you're right, but maybe @vadi2 can shed some light into why defenses are reset on Char.Name... I had no chance to test yet, but I would assume this even is also fired on title change...

**Comment by vadi2** [comment]
Is there an actual issue with this that you're investigating? ``offline_defences`` is for defences that stay through QQ like dragonform, and the reset call is to reset defences that don't stay through QQ - you'll see it doesn't actually reset all defences:

```
    if not defs_data[def] or (defs_data[def] and not defs_data[def].stays_on_death) then
      defc[def] = nil
    end
```

**Comment by bunster** [comment]
I'm afraid I don't understand. It looks like (to me) it is being done in a fashion that adds the offline defences on systemstart and then removes them again upon login. I do see that it doesn't reset *all* the defences (it keeps the ones that stay upon death). But it will reset the ones that are added from the offline_defences file. So you'll always log in with reset defences (defc as an empty table).

**Comment by vadi2** [comment]
That's intended, you lose defences when you QQ.

**Comment by bunster** [comment]
Oh. I did not know that was its intended purpose... My apologies. :disappointed:

**Comment by keneanung** [comment]
But what's the point of offline defenses then?

**Comment by vadi2** [comment]
Some defences stay, like dragonform, vengeance, soulcage - they need to be
remembered. See offline_defences list. Others don't, so they need to be
reset.

**Comment by keneanung** [comment]
@vadi2 I made my question clearer in an edit:

> Edit: I mean... You describe it as this:
> `offline_defences` is for defences that stay through QQ like dragonform
> and that is what the `defload` function does: It calls `defences.got(defense)`, which adds the defense to `defc`. The code quote from `reset.defs()` you used above, removes everything from `defc` again if it doesn't stay through death... There is no check for offline defs in there

**Comment by vadi2** [comment]
See ``and not defs_data[def].stays_on_death``, so something like Dragonform is not reset.

**Comment by keneanung** [comment]
That checks `stays_on_death` and not `offline_defense` :confused:

**Comment by vadi2** [comment]
```
  defs_data:set("dragonform", { type = "dragoncraft",
    offline_defence = true,
    invisibledef = true,
    **stays_on_death = true,**
    on = "You already maintain the form of the Dragon.",
    off = "Your draconic form melts away, leaving you suddenly weaker and more vulnerable." })
```

**Comment by keneanung** [comment]
But we were discussing `offline_defence`... So either it is not really useful and should be removed or I'm still missing something.

**Comment by vadi2** [comment]
Delete offline_defences and you won't have Dragonform staying through Mudlet resets. Delete defs.reset() and you won't have the defences be reset when you QQ and relogin without restarting Mudlet. Both features are useful and used, absence of which will introduce issues.

Here are the relevant changelog entries, offline_defences was introduced with:

``- dragoncraft, soulcage, vengenace and transmog are now saved through restarts - system will remember you're in Dragon if you QQ'd as one``

reset.defs() on charname was introduced with:

``- fixed defences to be reset on logging out``

@bunster is correct in the original issue, the actual right thing to do here is not to call reset.defs() but something that ignores offline_defence instead.

**Comment by keneanung** [comment]
Ah, now we're on the same page :smile: Thanks for clearing this up!
