### ISSUE TITLE
Pipes eternally empty and refill

### ISSUE THREAD

**Issue by tltbdev** [svof/svof#171]
http://prntscr.com/amoe3r

Not sure how to really use github correctly or to get help, so here it is. Coming back after ~ 8 years away and no idea how to set things up correctly or fix the above problem.

**Comment by keneanung** [comment]
This is one possible way to get help :)

Did you check you `plist` in between? Often times pipe issues are fixed that way.

If that doesn't help, which svof are you at?

**Comment by tltbdev** [comment]
Which svof? Uh, Paladin.Svof.v16.

**Comment by keneanung** [comment]
@tltbdev does this issue still exist for you or was it fixed with the prompt?

**Comment by keneanung** [comment]
Closing as there's been no answer for a while now.
