### ISSUE TITLE
Documentation incorrect for svo.lasthitlimb

### ISSUE THREAD

**Issue by CUltiris** [svof/svof#183]
Confirmed not working for SVO version 15 or 16 for two different people.
I have verified this with a blank profile and a fresh SVO installation.

Built in parry strategies work fine, but the svo.lasthitlimb variable is not being populated

**Comment by CUltiris** [comment]
Looks like the variable is svo.me.lasthitlimb and it's just the documentation that's incorrect

**Comment by jgh713** [comment]
Bleepbloop
