### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lisbethae** [svof/svof#185]
The problem was: "[string \"function mmp.echo(what)...\"]:138: attempt to 
index local 'what' (a.

**Comment by keneanung** [comment]
Under which circumstances does this happen? What are you trying to do that doesn't happen or faulty?

**Comment by keneanung** [comment]
Also, did you have a look at http://svof.github.io/svof/namedb.html#troubleshooting ?

**Comment by lisbethae** [comment]
I sent it to you because Vadi told me to, I don't remember how or when I
got the error. Sorry.

**Comment by keneanung** [comment]
@vadi2 do you remember any details on this? If not I'm going to close this issue for now as it's pretty hard to replicate without further info.

**Comment by lisbethae** [comment]
Am on a course at present, I can research it in a week or so. I save all my
logs and if errors show on them, I can send what happened.

**Comment by keneanung** [comment]
Perfect. I will wait a while until closing this then :+1:

**Comment by jgh713** [comment]
Just wanted to point out that `mmp.echo(what)` is mudlet mapper, not svo.
