### ISSUE TITLE
Mass gets applied multiple times when refilled from rift

### ISSUE THREAD

**Issue by keneanung** [svof/svof#188]
> Sent By: Deladan On 5/30/22:45
> Svof refilling mass from rift fix right now it does 3 applies when you refill hopefully this will fix it http://imgur.com/O1uF5vZ.

**Comment by jgh713** [comment]
Fixed with gmcp.

**Comment by keneanung** [comment]
linking to gmcp PR: #209

**Comment by jgh713** [comment]
Neeeeeeeeeevermind. Was fixed from my testing but Del is still having the issue. No clue why.
