### ISSUE TITLE
Smoking while off smoke balance increases said balance

### ISSUE THREAD

**Issue by keneanung** [svof/svof#189]
> Sent By: Deladan On 5/26/0:03
> Http://pastebin.com/pP2pKaA6 it keeps trying to smoke like a lot afterwards.

It seems svof does not know that smoking while smoke off balance increases said balance. Not sure about other issues here

**Comment by jgh713** [comment]
Smoking while off smoke balance doesn't seem to increase smoke balance anymore.

http://pastebin.com/ncKMVDHn

**Comment by keneanung** [comment]
Will close this then, but we should keep an eye out for similar issues.
