### ISSUE TITLE
NDB Reconnecting

### ISSUE THREAD

**Issue by jgh713** [svof/svof#191]
Plenty of people have an issue where their ndb gets disconnected because they close/cancel, or for a couple other odd reasons. These people are unable to use ndb functions until they restart mudlet, at current, which can be a pain depending on the circumstances. Below is a fairly simple bit of code that reconnects (only if you're not connected) that should be added into an alias (ndb recon|reconnect?), or perhaps even better, added as a function that's checked before executing any ndb function (adds few ms delay when it reconnects, imperceptible otherwise), though echoes would need to be removed in that case.

```
if tostring(db.__conn.namedb) == "SQLite3 connection (closed)" then
    db.__conn.namedb = nil
end

if db.__conn.namedb == nil then
    ndb.init()
    svo.echof("Manually reconnected to the Name Database. Cancelling honours-checking so you can resume without issue.")
    ndb.cancelhonors()
else
    svo.echof("We're already connected to the Name Database.")
end
```

**Comment by jgh713** [comment]
Actually, hold off on this for now (assuming anyone's ever actually considered it). There's another issue that's popped up, tied into this. Looking into it.

**Comment by QwindorRousseau** [comment]
Pretty sure this was fixed from a previous update to fix the ndb functions. Closing for now until it comes up as an issue with the current version.
