### ISSUE TITLE
Inundated with phlegmatic humour detects slickness + loki instead of lethargy

### ISSUE THREAD

**Issue by ghost** [svof/svof#200]
Inundating the phlegmatic humour shows the system getting slickness and loki, instead of (hidden) lethargy.

**Comment by jgh713** [comment]
Gmcp tracks the proper afflictions (random from a pool of four, anywhere from one to four afflictions depending on severity of temper). This is still a bug, disabling the relevant alchemist trigger should fix it.

**Comment by Kogannn** [comment]
To add to this I do not believe it is random afflictions given. If tempered from 1-3 it just gives lethargy when inundated. 4-5 give lethargy and anorexia. 6-7 give lethargy, anorexia, and slickness. And 8 tempers to phlegmatic give lethargy, anorexia, slickness, and weariness. Have tested.

**Comment by jgh713** [comment]
Yeah that was outdated info. Is entirely deterministic nowadays.
