### ISSUE TITLE
Outdated Installation Instructions for Devs

### ISSUE THREAD

**Issue by caJaeger** [svof/svof#202]
On OSX, the instructions for installing lua and the dependencies is outdated, brew simply doesn't know how to associate luarocks, penlight, and the filesystem to lua5.1. It will always refer to lua 5.2.

(I have before created an entire build with 5.2, why stick with a deprecated version of lua?)

Ignoring the brew instructions I have successfully installed the 5.1 version of lua, building it from source, as well as the most recent version of luarocks, also from source. All dependencies installed as well. Everything checks out, with the exception of the actual system, attempting to generate a class fails with this error:

```
generate.lua:181: attempt to index field 'skills' (a nil value)
```

I would love to start looking into this but every time I do I spend a few hours trying to get the basic environment setup and when I do, the code doesn't run.

Perhaps i am just missing something.

**Comment by keneanung** [comment]
The build system may not need 5.1 (not 100% sure about that), but generally we stick to 5.1 because mudlet only supports that version.

I'll have a look into this issue later on, but in case it's a Mac specific issue, I can't help, cause I'm a linux user.

**Comment by caJaeger** [comment]
@keneanung Alright, that's good to know. Perhaps I will just stick to building in 5.2 and make a VM with Ubuntu or something.

**Comment by keneanung** [comment]
Just because I fiddled with Docker a lot lately and they released "native" Windows and Mac support (at least for some versions, but it worked okay on a windows 7 machine I tested), would you be willing to test that path for Mac?

It would allow Mac-Users to simply install docker and run a single command for building...

**Comment by natecox** [comment]
I'm a big fan of docker, but I think it may be a bit much to install just for this.

Install instructions for macOS should specify `luarocks-5.1 install <package>` at the least. As an aside, I switched to [asdf](https://github.com/asdf-vm/asdf) to manage Lua so this wasn't an issue for me. Highly recommend.

**Comment by QwindorRousseau** [comment]
This will no longer be a problem for developers as the bulk of the editing can be done in mudlet itself.
