### ISSUE TITLE
It is just me?

### ISSUE THREAD

**Issue by lisbethae** [svof/svof#204]
combine sigil;;drop group sigil
"svo:2929: attempt to index field 'item' (a nil value)"

"svo:2929: attempt to index field 'item' (a nil value)"

"svo:2929: attempt to index field 'item' (a nil value)"

"svo:2929: attempt to index field 'item' (a nil value)"

"svo:2940: attempt to index field 'item' (a nil value)"

"svo:2940: attempt to index field 'item' (a nil value)"

"svo:2940: attempt to index field 'item' (a nil value)"

"svo:2940: attempt to index field 'item' (a nil value)"

"svo:2940: attempt to index field 'item' (a nil value)"

"svo:2939: attempt to index local 'e' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2939: attempt to index local 'e' (a nil value)"

"svo:2939: attempt to index local 'e' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2939: attempt to index local 'e' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2939: attempt to index local 'e' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2939: attempt to index local 'e' (a nil value)"

"svo:2939: attempt to index local 'e' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

combine sigil
"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

ii sigil
"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

"svo:2928: attempt to index local 'n' (a nil value)"

Disconnected

alt-R to reconnect, get this nonsense.

", "attrib": "g" } }m": { "id": "78e"location": "inv", "item":5958"icon": "rune", "attrib": "g" } 
}icon"g" } }icon"g" } }icon"g" } }icon"g" } }icon"g" } }icon"g" } }icon"g" } }icon"45} }m": { "id": 
"78e"location": "inv", "item":5958"icon": "rlocation": "inv", "item":i728a95sme": "an eye sigil", 
"i728a95sme": "an eye sigil", "i728a95sme": "an eye sig0oation": "inv",", "icon": "rune", "attrib": 
"g" } }icon"g" } }icon"g" } }icon"g" } }icon"g" } }icon"g" } }icon"45} }icon"g" } }icon"g" } 
}icon"g" } }icon"g" } }icon"g" } }0e", "attrib": "g" } }icon"g" } }icon"g" } }ils", "icon": "rune", 
"attrib": "g" } }icon"g" } }icon"g" } }0e", "attrib": "g" } }icon"g" } }icon"g" } }ils", "icon": 
"rune", "attrib": "g" } }icon"g" } }icon"g" } }ar": { "id": "49600ame,4e": "an e7pdate { "loion"ar.
It4e": "a group of 534 ey926 eye sigils", "icon": "rune", "attr14date { "locat3"item": { "id": 
"7874ame": "an eye  group of 940 ey6498v"79umup of 9322aa group of 5aminv9pe": "an eye sigil", 
"i728a95sme": "an eye sigil", "i728a95sme": "an eye sigil", "i728a95sme": "aeItem" } }ar.Ims.Update 
{ "loion"ar.It4e": "a group of 534 ey926 eye sigils", "icon"5oe": "an eye sigil", "iconte6 534 ey926 
eye sigils", "icon": "rune", "attrib": "g" } }icon"g" } }icon"g" } }ar": { "id": "49600ame,4e": "an 
e7pdate { "loion": "an eye  group ot4e": "a group of 534 ey926 eye sigils", "icon"5oe": "an eye 
sigil", "iconte { ": "an eye  gr"ÉChar.Items.Update { "loid{ "id": "49600ame,4e": "an e7pdate { 
"loion"ar.It4e": "a group of 534 ey926 eye sigils", "icon": "rune", "attr14date { 
"locat3"item":950254557238", "item": { rob": "g" } }icon"g" } }icon"g"il", "icon": "} }m": { "id": 
"78e"l8 "an eye  group ot4e": "a group of 534 ey926 eye sigils", "icon"5oe": "an eye sigil", "iconte 
{ ": "an 3 "inv", "item": { "id": "78e"location": "inv", "item": { "id": "78745", "name": "a grob": 
"g" } }icon"g" } }icon"g" } }ar": { "id": "49600ame,4e": "an e7pdigil", "icon": "rune", "attrib": 
"g" } }icon"g" } }icon"g" } }icon"g" } }icon"45} }icon"g" } }icon"g" } }icon"g" } }ic: "} }m": { 
"id": "78e"l8 "an eye  group ot4e": "a group of 534 ey926 eye sigils", "icon"5oe": "an eye sigil",
}37, "i728a95sme": "an eye sigil", "i728a95sme": "an eye sigil", inv", "item": { "id": "7874a"inv", 
"item"01o3e65a group of 534 ey926 eye sigils", "icon"5oe":eigil", "i728a904.Ims }icon"g" } }icon"g" 
} }ar": { "id": "496004gil", "i728a95sme": "an eye sigil", "i728a95sme": "aeItems.Remove { 
"location": "inv", "item": { "id": "425em":i728a95sme": "an eye sigil", "i728a95sme": "an eygicon": 
"rune", "attr14date { "locat3"item":950254557238", "item": { rob": "g" } }icon"g" } }icon"g" } 
}icon"g" } }icon"45} }icon"g" } }icon"g" } }icon"45} }icon"g" ls", "icon": "rune", "attrib": "g" } 
}icon"g" } }icon"g" } }ar": { "id": "496004gil", "i728a95sme": "an eye sigil", "i728a95sme": 3 } 
}icon"g" } }icon"g" } }ar": { "id": "496004gil", "i728a95sme": "an eye sigil", 
"i728a9545m":i728a95sme": "an eye sigil", "i728a95sme": "an eye sigil", "i728a: "inv",
458eye525n"uw5p.Update { "loepe5 "an eye sigil", " "location": "inv", "item": { "id": "48872ame": 
"an eye sigil", " "location7 "a grou355s.Update { "locatio"icon": "rune"665H5 } }icon"g" } }icon"g" 
} }ar": { "id": "496004gil", "i728a95sme"n eye sigil", "i728a: "inv",458eye525n"uw5p.Update { 
"loepe5 "an eye sigil", " "location": "inv", "i5dúicon"g" } }icon"g" } }icon"45} }, "i728a95sme": 
"an eye sigil", "i728a: "inv",458eye525n"uw5p.Update { "loepe5 "an eye sigil", " "location": "inv", 
"item": { "id": "48872ame": "an eye sigisme": 3 } }icon"g" } }icon"g" } 6926 eye sigils", "icon": 
"rune", "attrib":ar.Items.Update { "loid{ "id": "49600ame,7} }icon"g" } }icon"g" } }l2con"g" } 
}l2con"g" } }l2con"g" } }l2con"g" } }l2con"g" } }l2con"g" } }l2con"g" } }i728a95sme": "an eye sigil",
 "i728a95sme": "an eye sigil", "i728a: "inv",458eye525n": "invup n eye  "} } ": "an eye  group of 
93a eye sigils", "icon": 6emove { "locd.3 }, "i728a95sme": "an ey05on eye s94o/o/id": 
"78745"28a95sme": "an eye sigil", "i728a95sme": "an eye sigil", "i728a95sme": "an eye sig0oation": 
"inv",", "icon":Il ey": "rune", "atsigils", e8 .ation"up of 53": : "aocat6i908b254nvg4riioation"up 
of 53iroup of 54eye sigils", e8{ "id"0": "a9600ame,7} } ": "an eye  group of 93a eye sigils", 
"icon": 6emove { "locd.3 }94o/o/id": "78745"28a95sm46 eye sig5h} ey926 eye sigils", "icon": "rune", 
"attrib":ar.Items.Update { "loid{ "iil", "i728a904.Ims }9i5995sme": "an ey05on eye s94o/o/id": 
"78745"28a95sme": "an eye sigil", "i728a95sme": "an eye sigil", "i728a95sme": "an  } }94o/o/id": 
"78745"28a95sme": "an eye sigil", "i728a95sme": "an eye sigil", "i728a",
o/o/oo/o/o/o/o/o/oo/o/o/o/o/o/oo/o/o/o/o/o/oo/o/o/o/o/o/oo0 "location": "inv", con"5oe": "an 7eye  
group of : "an eye sigil", "icon": "} }94o/o/id": "78745"28a95sme": "an eye sigil", "i728a95sme": 
"an eye sigil", "i728a",oame,7} }94o/o/id": "787.04si728a95sme": "an eye sigil", "i728a95sme": "an 
eye sigil", "i728a: "inv",458eye525n": "invup n eye  18745"28a95sme": "an eye sigil", "i728a95sme": 
"an eye sigil", "i728a95sme": "an  } }94o/o/id": "78745"28a95sme": "an eye sigil", "i95sme": "an eye 
sigil", "i728a",o/o/oo/o/o/o/o/o/oo/o/o/o/o/o/oo/o/o/o/o/o/oo/o/o/o/o/o/oo0 
"location":6/o/o/o/o/o/o/o/o/o/ eye  grou24har.Item.Items.Update { "locatio"icon": "rune"665l9": 
"invup 891i ey926alocation": "invg4riioation"up of 53": : "aocat6icon"g" } }icon"g" ls", "icon": 
"rune", "attribo/o/o/o/o/ eye  grou24har.Item.Items.Update { "locatio"icon": "rune"665l9": ame,7} 
}94o/o/id": "78745"28a95sm46 eye sig5h} ey926 eye sigils", "icon": "rune", "attrib":ar.Items.Update 
{ "loid{ "iil", "i7on": "1v", "ite} n"5": "rune", H.It } }94o/o/id": "787.04si728a95sme": "an 
ey504si728a95sme": "an ey504si728a95sme": "an ey504si728a95sme": "an ey504si728a95sme": "an 
ey504si728a95sme": "aN3 }94o/o/id": "78745"28a95smf 5aminv9pi728ab 81p of 9322aa group of 5amiroup 
of 5amiro/o/o/o/o/o/o/o/o/o/o/o/o/o/o/o/o/o/o/o/o/o678745"28a95sme": "an eye sigil", "i728a95sme": 
"an eye sigil", "i728a",oame,7} }ic33grou24har.e sigil", "i728a95sme": "an  } }Rapture Runtime 
Environment v2.3.10 -- (c) 2016 -- Iron Realms Entertainment
Multi-User License: 100-0000-000

           ******************************************

**Comment by jgh713** [comment]
Looks like a known mudlet 2.1 bug. Have you tried restarting Mudlet?

Typically happens when you receive too many lines at once, for instance picking up 750 ungrouped commodities or something. Was fixed in 3.0. Restart should do it.

**Comment by lisbethae** [comment]
it would have been 2 groups of sigils. (it did it, btw, and then it made me speak in tongues, I'll reboot, I just upgraded.....)

**Comment by jgh713** [comment]
Well, restarting on its own (sometimes twice) should fix your problem. Upgrading to 3.0 will make it not happen again!

**Comment by keneanung** [comment]
Did that happen again after restarting? (Can you reproduce it?)

**Comment by lisbethae** [comment]
All is well. Cannot reproduce. Upgraded, restarted computer, restarted
mudlet

**Comment by keneanung** [comment]
I'll close this issue then :smile:
