### ISSUE TITLE
Relighting and svo.sendc

### ISSUE THREAD

**Issue by jgh713** [svof/svof#205]
Svo doesn't properly recognize emptying pipes as a command that requires balance, so when used in conjucnction with sendc, relighting doesn't work properly, and just outrs a lot of whatever plant/mineral and spams attempting to empty/relight.

Not sure where or how one would address this, so if someone could take a look, that'd be great.

**Comment by keneanung** [comment]
It may be enough to replace the send in https://github.com/svof/svof/blob/master/raw-svo.rift.lua#L664 and following by a `doaddfree()`. (https://github.com/svof/svof/blob/master/raw-svo.rift.lua#L707 as well)

**Comment by QwindorRousseau** [comment]
@svof/developers Again lets take a look and see if this is still an issue and if it is then above information should make this an easy fix.
