### ISSUE TITLE
Problem with the people tracker, or so says e!

### ISSUE THREAD

**Issue by lisbethae** [svof/svof#206]
The problem was: "...\\*usernamehere*\\.config\\mudlet\\profiles\\Achaea/Druid svo/svo:44267: attempt to _concatenate_ field '?' (a nil value)"

**Comment by keneanung** [comment]
Could that have been a sense ability with A LOT of copies of a room name on the database? (That#s what a cursory look at that line reveals at least)

**Comment by jgh713** [comment]
@keneanung it's an issue with the mapper, there's a bug that's preventing mmp.init() from running properly (I think a fix is waiting to be pushed?), so when checking area names and the like, things break. It also causes issues with RF, location, gotop, and some other oddities.

At least, from what I've seen. *shrug*

**Comment by keneanung** [comment]
Closing this as the info doesn't help analyzing and no answer on questions.
