### ISSUE TITLE
Travis.ci build

### ISSUE THREAD

**Issue by jgh713** [svof/svof#212]
So the travis build doesn't actually fail if there's an issue and it can't complete the build. It just errors on the first class package (shown in the log) then exits as a successful build. Not sure how relevant this is, but it'd be nice to not have to scrutinize the log each time to see if things break when pushing changes.

Idk, just seems logical.

**Comment by keneanung** [comment]
I made te changes in 5a68217a8e47690a4e92eefd2aa2e473dce25c7f (and hoped I'd get to merge that branch in quick enough). I'll cherry-pick it later.
