### ISSUE TITLE
Pear keepup

### ISSUE THREAD

**Issue by jgh713** [svof/svof#214]
Not -super- familiar with the defs process. Would there be a decent way to have this on keepup at all times but only defup when necessary?

**Comment by keneanung** [comment]
Isn't it already working like this (more or less)? Take drowning damage and it kind of goes on keepup and the popping message reapplies it.

**Comment by jgh713** [comment]
Well, if you drown and take damage it'll keep up, and then when it wears off and you take damage again it redefs it. That's 1-2k (if not more) damage on a relatively steady interval that's completely avoidable. Should be handled the same way serverside handles it (only defs it up when underwater, but immediately defs on entering and keeps it up down below).

**Comment by keneanung** [comment]
I thought it'd redef on popping message. If not, maybe that would be a viable middle ground for now?

**Comment by canuck314159** [comment]
Does svof already track what the gmcp room type is?  

You'd have to preemptively know when you're underwater which would be a bit of a performance hit on the system to check that.  Yeah, I think having it re-def on popping makes sense as long as it doesn't re-def when you're out of the water.  If it is the same popping message then you'll need to check if you're still underwater on every pop and only re-def if you're under water.

**Comment by keneanung** [comment]
It doesn't keep track of room types right now, but I don't think it would be too much of a performance strain.

I am pretty sure both popping messages are different.

**Comment by jgh713** [comment]
Yeah, performance wouldn't really be a major issue, especially if you used an internal variable for it instead of repeatedly checking details (which would be a minor minor improvement).
And last I checked they're the same def lost message.

**Comment by jgh713** [comment]
Turns out they are different messages, though that doesn't solve the original damage taken. Will look into implementing this soon.
