### ISSUE TITLE
Cloaking and shroud are the same defence.

### ISSUE THREAD

**Issue by jgh713** [svof/svof#215]
Should be merged into the same defence. Not sure what all that's going to entail, or if that's going to wreck anything, but they're the same, mechanically speaking. Shadowcloak, serpent cloaking and necromancy shroud give you the same defence, but are handled separately (shadowcloak is necro shroud).

**Comment by jgh713** [comment]
Best way to do this is probably just change serpent cloaking to shroud.

Maybe add got_ and lost_cloaking functions as an alias for shroud, for compatability reasons.

**Comment by jgh713** [comment]
Going to wait till someone else weighs in though, in case I'm missing some obvious explosion waiting to happen.

**Comment by keneanung** [comment]
I can't really see any issues. So if you want go ahead, whoever wants to take this.

**Comment by keneanung** [comment]
#246 is a workaround for the gmcp part of the issue but in the long run, they should be merged.

**Comment by QwindorRousseau** [comment]
@svof/developers again take a look and see and do a quick fix for it. Will probably need to add in a class check to do the right command for it but should be fairly easy.

**Comment by QwindorRousseau** [comment]
there isnt much of a reason to do this because of the different commands for each. the system recognizes it as the same defense in the end with the gmcp and the lines but need to keep commands seperate.
