### ISSUE TITLE
Recognizing hypothermia/frozen combo

### ISSUE THREAD

**Issue by Eguzki27** [svof/svof#221]
Svo erroneously assumes you're not frozen when you touch tree with hypothermia and frozen affs because tree doesn't cure anything. Ideally I want to not touch tree at all in this situation (unless I have other affs).

**Comment by keneanung** [comment]
Hrm, from my search this may need a change in the tree scenarios directly. I'd also like to generalise this, so other afflictions that are blocked/buried below other affs are attempted to be cured. But I am not sure, if I can easily get this information in the scenarios.
