### ISSUE TITLE
gmcp detection of (at least) deathsight not working

### ISSUE THREAD

**Issue by keneanung** [svof/svof#233]
As a workaround for a new deathsight message, #232 got implemented. However, gmcp tracking should still work...

The interesting part is a manual call to `svo.defs.got_deathsight()` works. And this function also _seems_ to be called by gmcp...

**Comment by jgh713** [comment]
This seemed to be an issue with nightsight at one point as well.

**Comment by jgh713** [comment]
As an update, this happens with deathsight, nightsight, and on occasion it happens with other general defences. It doesn't happen with anti-illusion disabled, so I'm assuming an illusion check is the root of the problem.

**Comment by jgh713** [comment]
Marking #268

**Comment by keneanung** [comment]
Fixed with #268
