### ISSUE TITLE
New Class: Depthswalker

### ISSUE THREAD

**Issue by jgh713** [svof/svof#238]
New class: Depthswalker

Skillsets: Aeonics, Shadowmancy, Terminus

New Defences:

  In Aeonics:
  
    Blur
	on: With a minor application of will, you increase your speed.
	off: This defence has no removal message, nor are gmcp events working properly for it. Seems to last 8:20 unboosted and 16:45 boosted.
	command: "chrono blur" or "chrono blur boost", preferably based on a 'vconfig boostblur' or some such. If no vconfig, then default no boost.
	
	
  In Shadowmancy:
	
	Shadowcloak
	"a grim cloak"
	"Shadow cloak" to summon.
	Requires full mana to create or summon if not present.
	
	Disperse
	gamename: disperse
	"Shadow disperse" to def.
	Requires shadowcloak, does not fade, takes equilibrium.
	
	Shadowveil
	gamename: shadowveil
	"Shadow veil" to def.
	Requires shadowcloak, does not fade, takes equilibrium. This ability also defs hiding.
	
  
  In Terminus:
  
    All of the following abilities require "word balance", which will need to be tracked via triggers, as there is no gmcp for it.
  
    Trusad
	gamename: precision
	command: intone trusad
	
	Tsuura
	gamename: durability
	command: intone tsuura
	
	Kail
	gamename: prismatic
	command: intone kail
	Requires and consumes eq, as well.
	
	Ukhia
	gamename: ?
	command: intone ukhia
	
	Qamad
	gamename: ?
	command: intone qamad
	
	Tah'maal
	No gamename, not tracked. Presumably a one-time empowerment, similar to runic armour. Likely not necessary to track, and overly complicated.
	
	Mainaas
	gamename: bodyaugment
	command: intone mainaas
	
	Gaiartha
	gamename: antiforce
	command: intone gaiartha
	
Active cure ability: 

    Accelerate
    command: chrono accelerate [boost]
    Boosted cures two random afflictions, otherwise it cures one. Requires and consumes eq
    use: You accelerate your body's ability to purge afflictions a thousandfold.
    off cd: You may accelerate time to cleanse your afflictions once again.
	
	
New tracking:

  Word balance:
  Is used for Terminus abiliites. 
  Balance returned: You may intone another word of power.
  Balance lost:
	Your mouth falls open as the all-consuming litany pours forth, and you know that in moments all that hear shall serve your will.
	^Imbuing your voice with power, you intone, "\S+"\.$
	^Directing your voice so only \w+ may hear, you command him to serve\.$
	You have not recovered enough to intone another word of power.
	^Turning to face \w+ you utter, "Ura?iad"\.$
	^You speak words of power over .+\.$
	Taking a steadying breath, you turn your focus inward and proclaim, "Mainaas".
	Drawing on ancestral memory, you let the lament of deSangre pour forth:
	
  Age:
  Is used for boosting Aeonics abilities
  Fades over time
    You have now aged yourself by (\d+) years.
	The effects of your time manipulation fade somewhat, leaving you only aged by (\d+) years.
	You are no longer artificially aged due to having manipulated time.
	
New afflictions:

    Affliction:         Degenerate
    Diagnose:           weakened in body.
    Afflicted msg:      none
    Cured msg:          You suddenly feel much less weak, strength flooding back into your limbs.
    Cure(s):            Time
	
    Affliction:         Depression
    Diagnose:           depressed.
    Afflicted msg:      Everything seems so pointless.
    Cured msg:          Maybe things aren't so bad after all.
    Cure(s):            Eat Goldenseal / Eat Plumbum

    Affliction:         Deteriorate
    Diagnose:           weakened in mind.
    Afflicted msg:      none
    Cured msg:          Your mental faculties suddenly recover.
    Cure(s):            Time
   
    Affliction:         Hatred
    Diagnose:           inspired to great heights of loathing.
    Afflicted msg:      An all-consuming hatred for everyone and everything suffuses you.
    Cured msg:          Your total loathing for everything fades.
    Cure(s):            Time
	
    Affliction:         Parasite
    Diagnose:           tormented by a parasitic curse.
    Afflicted msg:      You feel your strength being leeched away.
    Cured msg:          The leeching of your strength comes to an end.
    Cure(s):            Eat Kelp / Eat Aurum

    Affliction:         Retribution
    Diagnose:           suffering the curse of retribution.
    Afflicted msg:      A terrible sense of foreboding descends upon you.
    Cured msg:          The terrible sense of foreboding lifts.
    Cure(s):            Eat Bellwort / Eat Cuprum

    Affliction:         Shadowmadness
    Diagnose:           going slowly insane.
    Afflicted msg:      Your sanity begins to escape you.
    Cured msg:          Your sanity reestablishes itself.
    Cure(s):            Eat Goldenseal / Eat Plumbum

    Affliction:         Timeloop
    Diagnose:           stuck in a feedback loop.
    Afflicted msg:      The world seems to grow distorted around you, as if through a thick fog.
    Cured msg:          You break out of the feedback loop.
    Cure(s):            Eat Bellwort / Eat Cuprum

**Comment by jgh713** [comment]
Will add more applicable information if I come across it, or feel free to ask and I'll check something.

**Comment by jgh713** [comment]
Ignore the blur stuff. Gmcp is working properly now.

**Comment by keneanung** [comment]
I think the afflictions should go into a separate PR from the depthswalker defenses and so on.

**Comment by keneanung** [comment]
Are we possibly missing paradox here? That one might be an important one to adapt curing to

**Comment by keneanung** [comment]
~~~
Ginovianna delivers a lightning-fast strike to you with a scythe of shadows.
As the weapon strikes you, it burns with a sickly yellow light.
Everything seems so pointless.

Ginovianna lays into you with a savage blow from a scythe of shadows.
As the weapon strikes you, it burns with a sickly yellow light.
Everything seems so pointless.

Ginovianna raises an insubstantial dagger and points it at you with a sinister smile.
The shadow of Ginovianna suddenly comes alive, leaping forward to hammer at your shield in a silent 
frenzy of blows. Your protection lasts mere moments before exploding in a shower of prismatic shards.
~~~
Reap, Cull, Strike in that order

**Comment by keneanung** [comment]
Basic functionality released with version 25

**Comment by vadi2** [comment]
Great work!
