### ISSUE TITLE
got_ function missing issue

### ISSUE THREAD

**Issue by Storme87** [svof/svof#240]
The problem was: got_ function was nil for defence hiding (gmcp:hiding)

This is the line prompting the above error from using the Veil ability in Shadowmancy:

Summoning the shadows to coalesce about your person, you vanish into their stygian embrace.

I'm using the None (Classless) zip at this time to experiment with the Depthswalker class.

It also showed up in Defences list when I pulled up the defences to see what I put up.

**Comment by keneanung** [comment]
This will be addressed for the Depthswalker class package with #239. Not sure when I'll look into the more general issue.

**Comment by jgh713** [comment]
Unsure how this should be addressed, if at all. Is (currently) a reliable indicator when there's an issue regarding svo not handling a particular defense correctly, and means something should be fixed asap (and is almost always an extremely simple fix).

**Comment by keneanung** [comment]
Closing this for now as I agree with @jgh713 about it being an indicator that some internals are wrong...
