### ISSUE TITLE
got_ and lost_ functions not working properly.

### ISSUE THREAD

**Issue by jgh713** [svof/svof#244]
So, not sure if this was a change at some point or if everything's just up in the air, but none of the got_ or lost_ functions for defenses seem to work at all, even though the function definition is super simple:
` defs["got_" .. k] = function () defences.got(k) end `
defences.got() seems to work just fine when called locally, but the got_ and lost_ functions don't change anything when called via trigger or vlua. Workaround is in place for gmcp affs/defs, but these functions need to be fixed or phased out of the trigger package at some point.

**Comment by keneanung** [comment]
The got_ and lost_ functions seem to work when called from the tempRegexTriggers in the def table. But those also use the published svo.defs.got_ stuff... :confused:

**Comment by jgh713** [comment]
Nevermind.

**Comment by vadi2** [comment]
An explanation for historical purposes would be good, in case it happens
again.

**Comment by jgh713** [comment]
Not entirely sure, @vadi2. It wasn't working for the past few weeks, then moved to a new computer, compiled there, and it worked fine on both machines. Super confusing, but I don't have a clue.

**Comment by keneanung** [comment]
At least for deathsight gmcp __was not__ working through the `got_` function...
