### ISSUE TITLE
Add one-liner to install svof

### ISSUE THREAD

**Issue by vadi2** [svof/svof#283]
It should be possible to install svof with a one-liner ala [brew](https://brew.sh/), it'd be faster for the user than going through a download and install.

See https://gist.github.com/vadi2/28c0a469aa3022a99f872f8765e85221 for instructions on how to create one.

**Comment by QwindorRousseau** [comment]
@vadi2 Would you say to still look into this or are we going to be good with the in-client release?

**Comment by vadi2** [comment]
Since in-client should be installed as a module, this won't exactly work. This method is great for packages.
