### ISSUE TITLE
Remove inking alias from tattoo inker

### ISSUE THREAD

**Issue by keneanung** [svof/svof#295]
> Message #831        Sent by Lynara
2017/3/08/22:17 The 'inking' alias and outrifting such should be removed from svof, Achaea does that 
natively now and it gets all broken when you try to use the svof version. triggers are still good 
for it, because they pause the system and all that.

**Comment by nylian** [comment]
How do we want to adjust this? Personally I'd rather take everything SVO related out, except for the pause -
 including the "be still" comment and the retries.  Getting caught in an attack while trying to tattoo is frustrating and potentially robs a bunch of inks.

**Comment by keneanung** [comment]
Another option would be to allow the configuration of "max retries" and allow the inking process to get interrupted manually. I'm a bit careful to remove a feature as some people might consider it useful.

**Comment by QwindorRousseau** [comment]
Fixed with #394
