### ISSUE TITLE
Make Svof reloadable

### ISSUE THREAD

**Issue by vadi2** [svof/svof#3]
Right now if you make a change in the core Lua files, you have to restart Mudlet in order to get the new changes in. It should be possible to keep the state and reload the system on the fly to make it easier to edit.

**Comment by vadi2** [comment]
I'm adding 100 bounty credits to this.

**Comment by QwindorRousseau** [comment]
@vadi2 does this still need to be open with the new system?

**Comment by vadi2** [comment]
Nope - already did this myself
