### ISSUE TITLE
Attempting to cure Hellsight during Inquisition.

### ISSUE THREAD

**Issue by mattnorr** [svof/svof#303]
https://ada-young.appspot.com/pastebin/nA5vavem

In the above log you will see the issue.
While under the effects of Devotion INQUISITION the victim is incapable of curing the affliction HELLSIGHT. However, svo will attempt to cure it over and over, serverside curing will not. As you can see in the log, this is -strongly- punished by the AIRDISRUPT affliction, which causes a 7% mana drain on every SMOKE attempt.

For proper curing, svof should not attempt to cure hellsight during inquisition. It should however continue to cure other pipe-cured afflictions.

**Comment by keneanung** [comment]
as @jgh713 said in the other issue:
> Addressed with #305. The checks were in elm, not valerian. Not sure why.
