### ISSUE TITLE
"Use focus while you have spiritdisrupt." option request.

### ISSUE THREAD

**Issue by mattnorr** [svof/svof#304]
Priests have access to an affliction "spiritdisrupt" in their HEALING tree. While you have this affliction, any FOCUS attempt will succeed as normal, but you will also fall victim to another random disrupt affliction from the Priest. Since a lot of these disrupts are focusable themselves, this usually ends up with focusing being a net loss. This is especially true because the more disrupts you are victim to, the easier it is for the Priest to afflict you with INQUISITION.

Please allow for an option identical to the "Use Focus while you have cadmus" option already available in svof, except for the spiritdisrupt affliction instead.

**Comment by jgh713** [comment]
Addressed with #305. The checks were in elm, not valerian. Not sure why.

**Comment by keneanung** [comment]
I'm pretty sure that went to the wrong issue.

**Comment by QwindorRousseau** [comment]
Spirit disrupt is no more so issue has no purpose.
