### ISSUE TITLE
Editor issues

### ISSUE THREAD

**Issue by achaeansoandso** [svof/svof#319]
Hi!

So, the svo editor's breaking when I exit the editor sometimes. Seems like svo's missing a line from the trigger, and adding it fixes it. Could someone add this to the 'Out' trigger, in the Newsroom/editor folder? Thanks!

^You change builder bounty #\d+'s content\.$

**Comment by QwindorRousseau** [comment]
@svof/developers lets take a look at this just to make sure its good and add things as needed.

**Comment by DazedxJoker** [comment]
I've never seen that line before, it looks like it might be from editing as a mortal builder or something.

**Comment by QwindorRousseau** [comment]
we can add the line to the editor trigger anyways as even if they are mortal builders they still have to edit in character as far as i know.

**Comment by QwindorRousseau** [comment]
fixed with #433
