### ISSUE TITLE
Update Svof developer setup instructions to use lfs

### ISSUE THREAD

**Issue by vadi2** [svof/svof#32]
Instead of the hardcoded list of xml files for installModule() in README.md which needs to be updated whenever a new addon is added, it should use lfs to find out the list of files and install all files that begin with svo and end with xml.

**Comment by keneanung** [comment]
Adding all plugin XML without filtering isn't going to fly either because we have conflicting plugins (limbcounters for example) and others are not included when creating svof for classes.

**Comment by QwindorRousseau** [comment]
This has been fixed with the in client updates.
