### ISSUE TITLE
Bliss random defenses

### ISSUE THREAD

**Issue by seriley** [svof/svof#320]
Bliss randomly adds some defenses.

One of them is Resistance. As a Palidin, I can set that through Chivalry, so if it is added by Bliss, then it will show up when I DEF and svo.defc.resistance = true. I use the defc flags. gmcp.Char.Defences.List also shows resistance.

Constitution is another that Bliss randomly adds. When that happens, it shows up as checked when I do DEF, but svo.defc.constitution = **false, not true**. I also checked, gmcp.Char.Defences.List. Constitution shows up there.

Toughness is another that Bliss will occasionally add. Like Constitution, it will be checked when I DEF but svo.defc.toughness=**false**. It does show up on gmcp.Char.Defences.List

The flags just need to be set/updated

**Comment by QwindorRousseau** [comment]
@seriley I think this might be ok with all the classes being put into the same package but if you could please confirm this it would be appreciated.
