### ISSUE TITLE
Errors encountered with Shaman's Spiritlore Silvanix INVOKE ARROWCATCHING

### ISSUE THREAD

**Issue by seriley** [svof/svof#323]
When I INVOKE ARROWCATCHING ON,
I get this error:     **The problem was: got_ function was nil for defence arrowcatch (gmcp:arrowcatching)**
followed by these two output lines:
**You feel poised and ready to intercept projectiles.**
**You have begun to look for arrows to pluck from the air.**

When I then DEF,
I get this error:      **The problem was: got_ function was nil for defence arrowcatch (gmcp:arrowcatching)**
and this output line after the tattoo def lines:
**You are attempting to pluck arrows from the air.**

When I INVOKE ARROWCATCHING OFF,
I get this error:     **The problem was: lost_ function was nil for defence arrowcatch (gmcp:arrowcatching)**
followed by the output line:
**You will no longer intercept projectiles.**

**Comment by QwindorRousseau** [comment]
@seriley Can you confirm this is still an issue with the in-client branch?
