### ISSUE TITLE
Minor error applying mending

### ISSUE THREAD

**Issue by druque** [svof/svof#328]
Error when the mending used is the last drop in the vial and achaea autofills the empty vial from the rift.

Svof doesn't expect the line starting: "You quickly refill a...." and doesn't register the mended limb as it should. I assume that other curatives (speed, caloric etc) need checking too.

Log text:

```
[Curing]: APPLY MENDING TO LEGS
You take out some salve and quickly rub it on your legs.
You have emptied an oaken vial of its salve.
You quickly refill an oaken vial with a salve of mending from your rift, bringing the total sips remaining in your rift to 483.
The bones in your left leg mend.
(e!)89% 7546h, 97% 6838m, 77%e, 93%w S|SE|SW 8% cekdb  [bld(60) ?] 
```

(e!) error text:
`(svof): The problem was: unknowncrippledleg failed to complete: ...me/user/.config/mudlet/profiles/Druque/Priest svo/svo:23943: attempt to call field '?' (a nil value)`

**Comment by QwindorRousseau** [comment]
@svof/developers lets make sure this isnt an issue as this would mess with several things as all vials refill from the rift if you have it in the rift.

**Comment by K1ngSpad3z** [comment]
Should just be able to change the multiline number to 2 on the apply trigger if the curing line is a seperate trigger. If not we can just copy the trigger over and create a line spacer for the rift fill and be fine either way. Simple fix regardess

**Comment by QwindorRousseau** [comment]
Issue was apparently fixed at some point. No idea when but there is no error with the rift filling the vial and capturing the cure.
