### ISSUE TITLE
Go to lesserform when doing vinstall

### ISSUE THREAD

**Issue by vadi2** [svof/svof#330]
Since skills detection is GMCP-based, class skills like rage and fitness will be disabled by default if you're in dragon when you do `vinstall` - because Achaea says you don't have them.

**Comment by QwindorRousseau** [comment]
@vadi2 should we just make a disclaimer echo when you switch classes to check the vconfig list to make sure it is active like they want it to be or not with the in-client covering all the classes now?

**Comment by vadi2** [comment]
This is about `vinstall` not catching what skills you have when you're in Dragonform.

**Comment by K1ngSpad3z** [comment]
This is going to be a rather harder fix as people with multiple classes will not be able to have all of their class skills marked off in vconfig. We can add in doing lesserform for vinstall but if they change to a different class they will still need to alter their configs accordingly. So I would say just add the lesserform into the vinstall and make an echo when you load a new class to check their configs

**Comment by vadi2** [comment]
You raise a good point about multi-class, but the echo is going to get annoying after you read it the first time. Perhaps leave it as-is
