### ISSUE TITLE
dragonform to lesserform

### ISSUE THREAD

**Issue by DanFronius** [svof/svof#331]
(svof): Saved system settings.
(svof): Welcome back!
(svof): Welcome back!

(svof): Loaded & ready to go, version 33.1 (homepage)
(svof): Changed your Svof from Black Dragon over to Infernal.
Your draconic form melts away, leaving you suddenly weaker and more vulnerable.
Your race is now that of Troll.
6911h, 4876m, 29550e, 20010w  db-10000-k0-s16:30:23.68--
6911h, 4876m, 29550e, 20010w  db-10000-k0-s16:30:23.98--
"[string "Script: Setup"]:1213: svo.addaff: what aff would you like to add? name must be a string"

"[string "Script: Setup"]:1213: svo.addaff: what aff would you like to add? name must be a string"

"[string "Script: Setup"]:1213: svo.addaff: what aff would you like to add? name must be a string"

Error console shows:

[ERROR:] object:<event handler function> function:<svo.classchange>
         <[string "Script: Setup"]:346: bad argument #1 to 'ipairs' (table expected, got nil)>
[ERROR:] object:<Do stuffs.> function:<Trigger557>
         <[string "Script: Setup"]:1213: svo.addaff: what aff would you like to add? name must be a string>
[ERROR:] object:<svo def start> function:<Trigger1139>
         <[string "Script: Parry"]:389: bad argument #1 to 'pairs' (table expected, got nil)>
[ERROR:] object:<svo cured slickness> function:<Trigger244>
         <[string "Script: Main trigger functions"]:2831: attempt to call upvalue 'aff' (a string value)>

**Comment by vadi2** [comment]
> (svof): Changed your Svof from Black Dragon over to Infernal.

Oh, that'd be the problem, GMCP is unreliable for knowing your class

**Comment by vadi2** [comment]
Well, not really unreliable since you are of a changed class - just need to put some workarounds in place.

**Comment by DanFronius** [comment]
the error didn't appear switching from Infernal to Runewarden and back, or going into dragonform though

**Comment by CorTheWin** [comment]
Pretty sure this is because it's trying to pull ab lists that don't exist in dragon from GMCP.

**Comment by vadi2** [comment]
Want to have a look at the code for that?

**Comment by CorTheWin** [comment]
willing to look, but haven't familiarized myself enough with the code that I want to edit things necessarily. (also I don't use SVOF myself and it becomes drastically harder to test changes) that being said:
[ERROR:] object: function:
<[string "Script: Main trigger functions"]:2831: attempt to call upvalue 'aff' (a string value)>
seems to be that 
if result.name == aff".._smoke" then 
has the concatenation inside the string accidentally.

**Comment by impuxi** [comment]
"[string "Script: Setup"]:1213: svo.addaff: what aff would you like to add? name must be a string"

I switched from Monk to Runewarden and got this when I went bashing. Is there a quickfix for it for now?

https://ada-young.appspot.com/pastebin/6DsYod7e

**Comment by impuxi** [comment]
Also, I think this is an issue along the same lines, but when I switched back to monk from RW it kept trying to defup RW stuff.

**Comment by vadi2** [comment]
That's a good catch, fixed that typo.

**Comment by CorTheWin** [comment]
Unless I'm missing a function call/define somewhere (which I probably am, I'm not super familiar with everything yet) I'm not sure where the function that calls this error message is used in triggers. Whereas that function is called in the dictionary. Will keep looking and familiarizing myself with the code though.

**Comment by CorTheWin** [comment]
Alright so non-intensive testing. In the dictionary are a bunch of calls that say something like: svo.addaffdict(svo.dict.cholerichumour)
when I go into mudlet and manually do Lua svo.addaffdict(svo.dict.cholerichumour) I get :       
<[string "Script: Setup"]:1213: svo.addaff: what aff would you like to add? name must be a 
string> (the error we've been seeing) 
this makes some sense because the output of Lua svo.dict.cholerichumour is
`{
  gone = {
    action_name = "cholerichumour",
    oncompleted = "function: 209062A8",
    name = "cholerichumour_gone",
    balance = "gone"
  },
  name = "cholerichumour",
  gamename = "temperedcholeric",
  sw = 12962,
  aff = {
    action_name = "cholerichumour",
    oncompleted = "function: 20901268",
    name = "cholerichumour_aff",
    balance = "aff"
  },
  herb = {
    oncompleted = "function: 20907DE8",
    inundated = "function: 20901148",
    onstart = "function: 20901248",
    offbalance = "function: 1A2852B8",
    mickey = "function: 1A285158",
    action_name = "cholerichumour",
    eatcure = {
      "ginger",
      "antimony"
    },
    balance = "herb",
    spriority = 40,
    name = "cholerichumour_herb",
    noeffect = "function: 20901128",
    cured = "function: 20900EE8",
    empty = "function: 20907B48",
    isadvisable = "function: 20907DC8",
    aspriority = 40
  }
}`
unsure of proper fix though.

**Comment by vadi2** [comment]
That's the correct output! If you have a look at https://github.com/svof/svof/blob/in-client-svof/svo%20(curing%20skeleton%2C%20controllers%2C%20action%20system).xml#L1295, svo.addaff works with a table as well as a string. It's historical - the old internal Svo API used a dict while the public one used just the affliction name as a string.

**Comment by vadi2** [comment]
@DanFronius actually what could help here is **vconfig log echo** , what does that show when this error happens?

**Comment by vadi2** [comment]
The fix by @CorTheWin is available here: https://github.com/svof/svof/blob/gh-pages/testing/Svof.v33.2.zip

Automatic update doesn't work yet, so you'll need to manually uninstall the old modules and install the new one.
