### ISSUE TITLE
Alchemist defup

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#337]
Here's a log with a few issues in it.

https://ada-young.appspot.com/pastebin/O0LVY7H5

**Comment by vadi2** [comment]
`(svof): svo.lifevision:  speed_purgative added with 'empty' call (nil)` is a normal debug message. What do the error messages actually say?

**Comment by DazedxJoker** [comment]
Not sure how it happens, the issues were somehow the precache variable was nil, and the debug e! were the similar to the the parry issue Taryius was having. I'm no longer able to recreate the isssue, as I somehow got the precache variable populated while trying to mess with it.

This is from around the same time: 

(svof): actions: deaf_herb timed out
(svof): expirein for deaf_herb set to 0.7
(svof): actions: doing deaf_herb
(svof): error from onstart(): [string "Script: Rift"]:309: attempt to index field 'precache' (a nil 
value)
(e!)(svof): actions: deaf_herb timed out
(svof): expirein for deaf_herb set to 0.7
(svof): actions: doing deaf_herb
(svof): error from onstart(): [string "Script: Rift"]:309: attempt to index field 'precache' (a nil 
value)
(e!)(svof): actions: deaf_herb timed out
(svof): expirein for deaf_herb set to 0.7
(svof): actions: doing deaf_herb
(svof): error from onstart(): [string "Script: Rift"]:309: attempt to index field 'precache' (a nil 
value)
(e!)(svof): actions: deaf_herb timed out
(svof): Warning, lag detected (while doing/curing deaf)

**Comment by DazedxJoker** [comment]
The only other issue in this log is there is no trigger calling: svo.dict.extispicy.physical.norat(). 

It looks like the code was put in if you didn't have a rat in your inventory but no actual trigger calling it was created:

Pattern lines would be:

You are not holding anything like that.
Perhaps you should try a deceased rat instead.

**Comment by vadi2** [comment]
I've put in a failsafe for the precache, that should cover it.

On the norat - seems like an issue present already, I'll leave it to someone else to have a look at.

**Comment by vadi2** [comment]
Please re-open if there'll be any issues in 33.4 beta! (unreleased as of right now)
