### ISSUE TITLE
Deafness during defup/keepup

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#338]
Seems to be having a similar isssue to parrying: 

(e!)(e!)(e!)(svof): Warning, lag detected (while doing/curing deaf)
[  LUA  ] - object:<error in Lua code> function:<no debug data available>
            <Lua error:[string "echo("The problem was: deaf failed to start ([string "Script: R...
"]:1: ')' expected near 'Script'>

**Comment by DazedxJoker** [comment]
Executing "ir" seems to fix this issue, because the precache variable was nil on a fresh install and was causing a problem with, curing and deffing up.

**Comment by vadi2** [comment]
Fixed with https://github.com/svof/svof/pull/329/commits/9ba8486a221fca3dd989635e73637d8051e6a853.
