### ISSUE TITLE
Curing Defenses not being removed on class switch

### ISSUE THREAD

**Issue by impuxi** [svof/svof#340]
Switched from Monk to Runewarden and got spammed with trying to put up the toughness defense. Only seems to be an issue when CURING DEFENCES ON

**Comment by vadi2** [comment]
They are removed though, see `vshowd`. I'm guessing in-game serverside curing system is the one that's spamming them?

**Comment by DazedxJoker** [comment]
Yea, I believe the issue is that they are being left on serverside defence keepup on class change.

**Comment by vadi2** [comment]
Seems to me that serverside shouldn't be putting up defences you don't have, tho?

We'll add a workaround to the system of course.

**Comment by vadi2** [comment]
So that's the easy fix for this? `CURING PRIORITY RESET`?

**Comment by vadi2** [comment]
Thanks to Atakrez for pointing out `curing priority defense list reset` - fixed with https://github.com/svof/svof/pull/329/commits/b6242a3a734571c88af6833bad3584559cf0ba26
