### ISSUE TITLE
"[string "Script: Curing skeleton"]:1293: table index is nil"

### ISSUE THREAD

**Issue by Brenex** [svof/svof#342]
Using SVOF 33.3, you can see here after I manually sit I receive the above error message:

![image](https://user-images.githubusercontent.com/3178983/35641302-c9a0e532-068d-11e8-91c9-c99766b11070.png)

**Comment by DazedxJoker** [comment]
Are you sure you're on 33.3? That was fixed and I'm not able to replicate it. Try doing a fresh install and delete the old modules?

**Comment by Brenex** [comment]
I realized I had not yet run vinstall so that might have been it. I wonder if there should be a reminder after installing modules in game, maybe after, "(svof): Loaded & ready to go, version 33.3 (homepage)" to run vinstall ASAP
