### ISSUE TITLE
svo.doaction() not functioning as documented

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#343]
I attempted the call the function as the example in the docs say, and received this error: 

vlua svo.doaction("thirdeye", "misc")

[  LUA  ] - object:<(vlua) Run lua code> function:<Alias182>
            <[string "Script: Action system"]:46: attempt to index local 'act' (a nil value)>

**Comment by vadi2** [comment]
Thanks, fixed with https://github.com/svof/svof/pull/329/commits/22c635e55f0407ae6b08d9df14a2eaa1ba33461b
