### ISSUE TITLE
blindness/deafness not and affliction

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#344]
Blindness and deafness don't seem to be reliably recognized as an affliction once removed from defup/keepup.

Tested on a non-Apostate.

**Comment by vadi2** [comment]
Is this with serverside enabled? Without it, it seems to work fine:

6700h, 6180m, 32400e, 29400w exk-vkeep deaf
(svof): Will keep deaf up.
(outr hawthorn|eat hawthorn)
You remove 1 hawthorn berry, bringing the total in the rift to 2278.
You eat a hawthorn berry.
6700h, 6180m, 32400e, 29400w exk-
You may eat another plant or mineral. (1.441s)
6700h, 6180m, 32400e, 29400w exk-
The aural world fades to silence.
6700h, 6180m, 32400e, 29400w exkd-vkeep deaf
(svof): Won't keep deaf up anymore.
(svof): deafness is now considered an affliction, will cure it.
(apply epidermal to head)
You take out some salve and quickly rub it on your head.
You are no longer deaf. (0.349s)
6700h, 6180m, 32400e, 29400w exk-
You may apply another salve to yourself. (0.914s)
6700h, 6180m, 32400e, 29400w exk-

**Comment by DazedxJoker** [comment]
Just did a little more testing, only getting the issue as a Monk so far.
