### ISSUE TITLE
slow curing mode

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#345]
It seems as if the system isn't respecting slow curing mode in some aspect. Note how it keeps trying to focus. Granted it is being blocked by the slow curing mode blockage, however I'm fairly certain that isn't how it is intended to operate.
 
https://ada-young.appspot.com/pastebin/Gu7LD62c

**Comment by vadi2** [comment]
Need to pin down the conditions it happens in - it looks like slowcuring is working correctly sometimes.

**Comment by macjabeth** [comment]
Any luck pinning this down? I tried with no success (and much frustration).. :/

**Comment by vadi2** [comment]
Nope

**Comment by macjabeth** [comment]
Removed my previous post asking since I -think- I found the issue, which was that `make_gnomes_work` was being called locally in `svo.loader.action`. If you change them all to `sym.make_gnomes_work` then you no longer get the async actions being called randomly in sync mode.

**Comment by macjabeth** [comment]
It holds up! I had already tested it before making the post, of course.

**Comment by macjabeth** [comment]
I'm sad to report that I've run into this issue again. :(

**Comment by QwindorRousseau** [comment]
@macjabeth Do you know if this is all good now or do I need to track this with the in-client version?

**Comment by macjabeth** [comment]
@QwindorRousseau I don't believe it's been added to the system yet. Implementing the catch I posted last year should patch it up, though you'll want to tests it first to confirm.

(I'd do it myself if I played Achaea and had a way to easily test it again, but I do not.)

**Comment by QwindorRousseau** [comment]
From what i can see if that he called it locally to make it svo.make_gnomes_work so it should be good now. Appreciate the feedback
