### ISSUE TITLE
Spamming hold command after unpause

### ISSUE THREAD

**Issue by Brenex** [svof/svof#346]
take a look at what I'm seeing after setting it up:

![image](https://user-images.githubusercontent.com/3178983/35719819-2e62fa60-07b9-11e8-982d-460625c70e49.png)
![image](https://user-images.githubusercontent.com/3178983/35719821-302ee0b6-07b9-11e8-9403-b48114ddc465.png)

**Comment by vadi2** [comment]
Sounds like you told the system to hold breath when you don't have the
skill.

**Comment by Brenex** [comment]
thanks, changed the vconfig on kaichoke although I wasn't being choked anyways?

**Comment by vadi2** [comment]
That option just turns breathing on for you automatically - you also could
have turned it on yourself.

**Comment by vadi2** [comment]
^ the system could be improved there to check GMCP skills to see if you've actually got the skill and turn it off in that case :)
