### ISSUE TITLE
Double prompt

### ISSUE THREAD

**Issue by VaskeNS** [svof/svof#348]
After installation of 33.4 version  I have a double prompt showing all the time. Doesn't matter if I enable single prompt or not as it remains the same. Also, it doesn't matter if it is a custom or standard prompt

Example
5666h, 4556m, exc 32.3- rat5666h, 4556m, exc 32.3- rat

**Comment by vadi2** [comment]
You sure you don't have two copies installed?

**Comment by VaskeNS** [comment]
actually when I try to login I get the svof message stating that I have double folders but I can't seem to locate where the double folders are.
