### ISSUE TITLE
Tekura Guarding

### ISSUE THREAD

**Issue by Antidas** [svof/svof#350]
As a Shikudo monk, Svof.v33.4 is trying to make me use guarding despite not having access to the skill. I've tried toggling off the guarding option multiple times, as well as downloading a new copy of the system and simply reinstalling a couple times. No matter what I do, I can't get it to stop trying to use guarding instead of parry.

**Comment by vadi2** [comment]
Is this something that the current non-beta v33 supports?

**Comment by impuxi** [comment]
Wanted to echo what Antidas said, I get it happening to. In the non-beta build, it works fine.

**Comment by impuxi** [comment]
It stops trying to put it up after I PARRY a limb.

**Comment by vadi2** [comment]
Fixed with https://github.com/svof/svof/pull/329/commits/aa64b0afbda68271757e223f0162c66eafc9bd9e
