### ISSUE TITLE
Multiclass keepup/defup issues

### ISSUE THREAD

**Issue by AlexGu100** [svof/svof#352]
Had resistance on keepup as Runewarden (Tri-trans), but when switching to Druid (0 lesson investment), SVO kept trying to morph hydra in order to put up resistance defence even though I did not have the Hydra skill. I also don't want resistance on keepup as Druid, while it is much more desirable as Runewarden, but since they are both considered "resistance," the only workaround is to make another defence mode.

**Comment by QwindorRousseau** [comment]
This is fixed with the in-client version as the old version does not support multiple classes.
