### ISSUE TITLE
Class Switch Bug

### ISSUE THREAD

**Issue by impuxi** [svof/svof#353]
I was in Runewarden and switched to Monk. The only defs it put back up were Grip and Weathering for class specific ones (assuming only because those are the only 2 class ones RW/Monk share). I can't VDEFS BASIC or VDEFS EMPTY -> VDEFS BASIC to get my class defs put up either. VSHOW DEFUP/KEEPUP both have all my class defs checked.

Maybe this is related to Rangor's issue? Turned serverside off and back on too for defenses. I restarted Mudlet and it didn't def me up in basic (usually does), but I was able to VDEFS BASIC after that to get my proper defs to go.

Tried going in and out of dragonform even and it won't put up the those class specific ones unless I manually type VDEFS BASIC.

If I had to venture a guess, it has something to do with DEFENSE PRIORITIES getting reset on class switch? If you reboot, it goes back to normal. No clue, just a guess!

**Comment by QwindorRousseau** [comment]
Is fixed in the current in-client version as the old version did not support multiple classes for defences.
