### ISSUE TITLE
ndb update all

### ISSUE THREAD

**Issue by Brenex** [svof/svof#354]
running this doesn't actually do anything. 

![image](https://user-images.githubusercontent.com/3178983/36320238-82258996-1313-11e8-85d2-95259b57544e.png)

**Comment by Brenex** [comment]
I changed it to the following and it works fine now:

`local names = {}
local alldata = db:fetch(ndb.db.people)

if #alldata >= 100 and not ndb.updateall then
  svo.echof("Are you really sure you want to re-check everybody in the database? You've got %d names - this'll take a while. If yes, do this again.", #alldata)
  svo.showprompt()
  ndb.updateall = true
  return
end
ndb.updateall = nil

for _, person in pairs(alldata) do
  table.insert(names, person.name)
end

local temp_name_list = {}
for i = 1, #names do 
  temp_name_list[#temp_name_list+1] = {name = names[i], xp_rank = -1}
end

db:merge_unique(ndb.db.people, temp_name_list)

svo.echof("Re-checking all %d known people in NameDB.", #alldata)
raiseEvent("NameDB got new data")`

**Comment by QwindorRousseau** [comment]
Fixed with #391
