### ISSUE TITLE
Nicator honors breaks ndb

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#355]
(svof): Honors on Nicator didn't happen - re-checking...
Lord Nicator, the Chosen One (male Human)
His birth was foretold in legend.
His rank among mortals needs no mention.
His credibility is without reproach.
He was the founder of the Seleucarian Empire.
He was the Champion of Humanity, as selected by Sarapis.
He was the first wielder of the Staff of Nicator.
7631h, 8183m, 32080e, 33565w cxkdb-
You have recovered equilibrium. (1.572s)
7631h, 8183m, 32080e, 33565w cexkdb-
(svof): Honors on Nicator didn't happen - re-checking...
Lord Nicator, the Chosen One (male Human)
His birth was foretold in legend.
His rank among mortals needs no mention.
His credibility is without reproach.
He was the founder of the Seleucarian Empire.
He was the Champion of Humanity, as selected by Sarapis.
He was the first wielder of the Staff of Nicator.
7631h, 8183m, 32080e, 33565w cxkdb-ndb cancel
(svof): Cancelled honors-checking people.

**Comment by Brenex** [comment]
same on my end

**Comment by CorenDuchai** [comment]
just needs the 'His birth was foretold in legend.' line added to the honors trigger
