### ISSUE TITLE
Setup documentation on Github Pages

### ISSUE THREAD

**Issue by vadi2** [svof/svof#36]
http://doc.svo.vadisystems.com will be retired and the documentation needs to be hosted on Github instead.

**Comment by alex-d-schroder** [comment]
Do we have permission to use your Sphinx source from the old documentation site?

**Comment by vadi2** [comment]
The source is in the repository already.

**Comment by keneanung** [comment]
If you don't mind, I'll set up something like https://gist.github.com/domenic/ec8b0fc8ab45f39403dd for  tags.

**Comment by vadi2** [comment]
Give it a go!

Look at precommit.lua on how to rebuild the documentation and update the
version number. That's one script I haven't gotten about to making more
generic.

**Comment by keneanung** [comment]
Gotta wait for the two PRS https://github.com/travis-ci/apt-package-whitelist/pull/1040 and https://github.com/travis-ci/apt-package-whitelist/pull/1036 to be merged. Otherwise there is no penlight and no LFS available.

**Comment by vadi2** [comment]
That's not really needed for building documentation, documentation just
requires python and sphinx. LFS and penlight would be needed for packaging
systems.

**Comment by keneanung** [comment]
I switched to the legacy build environment for now and got done what I planned to, even if I may or may not have done a little much.

Travis will now build all svo packages for a release, upload them to the release and build the documentation and commit it to the gh-pages branch, so it is available at the github pages.

I still need to clean up the commits (much trial and error was needed) and write the necesary steps to set everything up, then I will send in a PR.

Automated release upload example: https://github.com/keneanung/svof/releases/tag/14
Documentation is at http://keneanung.github.io/svof/

**Comment by vadi2** [comment]
Good stuff!
