### ISSUE TITLE
ndb.getinfo() site incorrect, and isn't this supposedly not used anymore?

### ISSUE THREAD

**Issue by ndsamuelson** [svof/svof#361]
https://github.com/svof/svof/blob/c15b782b52518b14d77d54bbc001c9f3db003fb0/svo%20(namedb).xml#L3283-L3286

from looking at the raw lua file vs this one, isn't the file download for honours not allowed? Maybe I'm getting two things confused. I've been gone a long time. Also, it seems to set everything to immortal even when I fix the site from oldsite.ironrealms to achaea.com.

**Comment by ndsamuelson** [comment]
I see. I'm using the most recent version that's stable,  and mine had oldsite.ironrealms.com instead of achaea.com in the download script, so I guess I'm confused. It's still setting everyone to immortal. I butchered up a fix for it and just made it never set anyone immortal no matter what but it doesn't pull anything from online at all anymore.

**Comment by vadi2** [comment]
Yes, the script needs to be updated

**Comment by ndsamuelson** [comment]
seems to be resolved with Brenex's pull request.
