### ISSUE TITLE
I cannot fathom the meaning of "showselfclasswho".

### ISSUE THREAD

**Issue by charicner** [svof/svof#367]
When I am trying to deffup with wuicksilver, or eat irid moss, I keep sending getting "I cannot fathom the meaning of "showselfclasswho"." back from the server

**Comment by charicner** [comment]
This is no occuring for everything, and I cant even use serverside healing, because it wont send the command for changing to serverside

**Comment by alex-d-schroder** [comment]
Right now, for some reason, when svof checks your command separator, it also picks up what's next to it in the CONFIG listing. So, when it tries to send multiple commands with your separator, it includes the whole "showselfclasswho" with it. It used to be, CONFIG had commandseparator on its own line but isn't anymore, that's probably why. I'll see if I can find the problem and put in a fix.

**Comment by alex-d-schroder** [comment]
Found it, I'll make a pull request for the fix in a bit, having some troubles with git (still learning). In the mean time, you can fix it locally in Mudlet, if you'd like.
Search for a trigger called "Config view command separator" in your profile/ Change the third trigger line from
^\| +CommandSeparator +(.+)? +\|
to
^\| +CommandSeparator +(.+)? +ShowSelfClasswho
Should fix the problem. Be sure to save the trigger and your profile after. If you reinstall svof before the fix goes in permanently, you'll have to redo this.

**Comment by vadi2** [comment]
That sounds quite right - looking forward to the PR. Let me know if I can help you with it
