### ISSUE TITLE
Druid defup

### ISSUE THREAD

**Issue by rzer0knight** [svof/svof#369]
Hi,

I seem to be running into an issue where I selected Hyena in defup. Typed vdefup basic and it starts to morph into a hyena, but immediately after getting balance it tries to morph again, screwing the morph. Did I just uninstall incorrectly or is it something else?

**Comment by vadi2** [comment]
Maybe transmorph or whatever that instant morph skill is enabled as an option by accident?

**Comment by rzer0knight** [comment]
I don't have transmorph or insta morph. I've disabled transmorph in vconfig

**Comment by rzer0knight** [comment]
Unless I'm mistaken, there's no config for disabling truemorph is there? Only one I see is for transmorph

**Comment by QwindorRousseau** [comment]
@rzer0knight do we still need to have this open for the in-client version?
