### ISSUE TITLE
Add rage tracking

### ISSUE THREAD

**Issue by vadi2** [svof/svof#4]
Add rage tracking - variable you can access, event on when it's changed, and a customprompt tag you can use to display it.

**Comment by QwindorRousseau** [comment]
I have some code that detects rage amount and saves it to a variable via gmcp. Who should i send it to?

**Comment by vadi2** [comment]
You want to submit a pull request with your changes - learn how to use Git and https://help.github.com/articles/using-pull-requests/.

**Comment by QwindorRousseau** [comment]
im just going to post this here right now until i figure out how to correctly do the pull request and such and update to svof as im still running the old paid version.

battlerage = battlerage or {}

function GetCharStat(type)
        local val = nil
        for i,v in ipairs(gmcp.Char.Vitals.charstats) do
                val = string.match(v, type:title()..": (.+)")
                if val then
                        return val
                end
        end
end

battlerage.amount = function ()
        return tonumber(GetCharStat("rage"))
end
