### ISSUE TITLE
Separate priority lists for affs/defs on serverside

### ISSUE THREAD

**Issue by vadi2** [svof/svof#40]
Serverside actually has 2 queues - one for afflictions, and one for defences. This isn't immediately obvious in documentation (and puts into question of what will happen if an affliction and a defence share a balance), but Svof right now treats them as in the same queue. Svof's feature of syncing priorities to serverside needs to split up affs and defs into two separate lists before updating them on serverside.

**Comment by QwindorRousseau** [comment]
As an addon to this is it already possible to set different prios per def profile so you could easily sway prios depending on who your fighting along with different health mana and moss percentages per profile without having to extensively code in auto prio swaps for your defence setup when you change to that defence setup

**Comment by keneanung** [comment]
@vadi2 I'm not sure what to do with this? #87 split afflictions and defences into 2 tables and people seem to be happier now. Is this closed with the mentioned PR?

**Comment by vadi2** [comment]
Okay, if it works, it works
