### ISSUE TITLE
Single prompt

### ISSUE THREAD

**Issue by QwindorRousseau** [svof/svof#405]
Forwarded issue again. Apparently the single prompt bugs out from time to time and requires a restart of mudlet to fix it until it does it again. Worth taking a look at the code at the least but I am not going to say high priority due to most people probably not using it all that much to be honest.

Edit: Issue she stated was that it will just vanish. This is with the current release version but I am putting as part of the in client as it might still be an in client issue. Will follow up with in game name when I receive it as it was over discord.

Edit2: Person who told me about this is Anandini.

**Comment by vadi2** [comment]
Get people to register issues themselves on Github or you'll be acting as a proxy forever... and we have no way of getting back to the original person. Like "bugs out" could mean anything, how can one start looking at it to fix the problem?

**Comment by QwindorRousseau** [comment]
This could possibly be from another bad interaction with the way the AK aff tracking script does things with the single prompt. Attempting to contact said person about it see if they were using it and if they are then I am closing this issue as its no on our side but rather because of another script trying to work around svo and people not listening to directions for certain system installs that they are warned about.

**Comment by QwindorRousseau** [comment]
Alrighty I have yet to hear anything back from said person about this and I am going to assume this is an issue with another script. Closing until someone else brings it up then we can see if it is because of the system or because of another script.
