### ISSUE TITLE
 Random Configuration Error on Vinstall

### ISSUE THREAD

**Issue by sdelo1185** [svof/svof#407]
"...o/.config/mudlet/profiles/Andraste Monk/Monk svo/svo:43229: attempt to concatenate field 
'mosshealth' (a nil value)"1

Encountered when doing vinstall. Persists through mutltiple install/uninstalls.

**Comment by QwindorRousseau** [comment]
I think this is one of the errors we keep running into where some of the vconfig options get messed up.

**Comment by DazedxJoker** [comment]
This looks like it wasn't for in-client Svo, but for Monk Svo.

**Comment by QwindorRousseau** [comment]
Closing due to this being for the old version. If issue persists through to the in-client version please reopen and tag it as such.
