### ISSUE TITLE
Error during Serverside Priority Sync

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#436]
In order to reliable create this error: Turnoff Serverside curing and force a classchange.

![image](https://user-images.githubusercontent.com/14912622/61603911-85272c00-ac0d-11e9-83a3-71f288485fec.png)

I believe the error is caused when sk.notifypriodiffs() runs into these when comparing differences.

![image](https://user-images.githubusercontent.com/14912622/61603760-d125a100-ac0c-11e9-929a-0d60e3c2c113.png)

**Comment by QwindorRousseau** [comment]
so we need to add in a check to not do it if svo serverside is not turned on?
