### ISSUE TITLE
Transition to gmcp-based affliction and defense detection.

### ISSUE THREAD

**Issue by Seifur** [svof/svof#44]
Implementing this would significantly reduce the size and complexity of the project.

##### There are a few things to note:  
Many abilities do not share the same name as the ones set in `svo.affl` and `svo.defc`
###### Afflictions
- **Bug:** There is no Add event when you gain an additional stack of a stackable affliction.
- **Bug:** There is no Remove event when you cure a level greater than 1 (cure level 2 -> now have level 1) of a stackable affliction
- **Add/List:** The name item contains a number in parenthesis for stackable afflictions.
- **Add/List:** The name item for humours does not contain a number
- **Add:** Hidden afflictions do not generate an event
- **Remove:** Is a 1 item length indexed table. The name is always just the base name. No numbers in parenthesis

###### Defences
(To be added later - needs more testing)

**Comment by vadi2** [comment]
Are all defences tracked, such as elementalism channels, angel and demon defences, harmonics, morphs, lyre, etc? I think there would be gotchas in defences as well.

**Comment by Seifur** [comment]
I think for defences it's only those that have a line in `DEF[ENCES]`, but would need to test various artefacts, harmonics, vibrations, etc.

**Comment by Seifur** [comment]
Just remembered that a decent number of the server names for both afflictions and defenses aren't the same as the ones set in `svo.affl` and `svo.defc`. We would need something to translate them over to maintain compatibility.

**Comment by vadi2** [comment]
The translation is already there as part of the serverside curing system, see "gamename" in svo.dict.

**Comment by QwindorRousseau** [comment]
Unknown afflictins via loki and blight ect ect could still be tracked via triggers for the system like it currently is then send a diag after a certain or manually update the affliction list via manual diag. Same has been true for torso breaks for some time so still a certain part of player input needed to sometimes keep up to date on curing. But with the gmcp table for afflictions it would help greatly in curing even in further class updates unless they add some completely new skill that does something different like fractures system and it would help with bashing as well in new areas.

**Comment by QwindorRousseau** [comment]
Would be a great leap for the system if we can get it to track via gmcp thats for dang sure as i know some people have messed with wundersys to track gmcp afflictions. The conversion would just take the time to test each affliction then pull it via gmcp then have it reference a table to set svo.gotaff i think is the api but not sure off the top of my head right now based on the gmcp name.

**Comment by slester** [comment]
Is anyone working on this already? I don't want to repeat work.

**Comment by Seifur** [comment]
I personally don't have the time for it so I haven't started at all. Best I can do at the moment is small cleanups.

**Comment by QwindorRousseau** [comment]
Got some code from Klendathu that might help in this as a base at least for the gmcp. I put it in kobra coding pad and saved a backup on my dropbox but if anyone wants to take it on that has more coding knowledge than me here you go.
https://kobra.io/#/e/-K-eTe1D8LKgiHk_MAqj

**Comment by OscarTG** [comment]
Hi, Klendathu here. I already use GMCP affs to affect Svo to a certain degree, especially where blackout's involved - eg gaining aeon, clearing entanglement, etc. I don't think gmcp affs are reliable enough on their own, but they could certainly be leveraged more.

**Comment by keneanung** [comment]
Care to share your implementation? I think everyone here agrees that they are not reliable (see noted bugs in the OP), But using them as a second layer to catch afflictions, they are certainly useful.

**Comment by OscarTG** [comment]
It's  bit messy, but you can get the general idea from here: http://pastebin.com/GDM8Kxw1

**Comment by keneanung** [comment]
And you are sure this does what it is supposed to do? The only definition for addaff, that I can find, expects a table (see https://github.com/svof/svof/blob/eff030c52a12836bbe009f74e090dc1db08fce97/raw-svo.skeleton.lua#L1327) and I am pretty sure you need to call svo.removeaff (which expects a name or an aray of names) when clearing an affliction...

**Comment by OscarTG** [comment]
I wrote it before serverside integration was included in Svo. It works for me

**Comment by keneanung** [comment]
So... Any takers?

**Comment by Seifur** [comment]
Maybe it would be better to make some new signals (`signals.gmcpcharafflictionslist`, `signals.gmcpcharafflictionsadd`, `signals.gmcpcharafflictionsremove`, `signals.gmcpchardefenceslist`, `signals.gmcpchardefencesadd`, `signals.gmcpchardefencesremove`) and connect the relevant functions to those. There's already an event function (`svo_gevents`) that calls `svo.gevents` to emit gmcp signals.

**Comment by keneanung** [comment]
That's the way I'd do it as well. And in thise functions I'd look up the
gamename (a dictionary would have to be set up, probably in
raw-svo.dict.lua in the function that autogenerates some entries into the
dict) and then get the dict entry and call addaff(dictentry) and
removeaff(name) (not sure about defenses).

James Nelson <notifications@github.com> schrieb am Fr., 16. Okt. 2015 20:12:

**Comment by keneanung** [comment]
Fixwd with #209
