### ISSUE TITLE
Non Target Applying Mass

### ISSUE THREAD

**Issue by impuxi** [svof/svof#457]
https://ada-young.appspot.com/pastebin/iFP6GDpF

Seeing this when other people apply mass, doesn't have to be target.

**Comment by druque** [comment]
Something is out of order. Clicking on the script in the window fixes it.
The limbcounter on mine is looking for svo.config which hasn't loaded yet.

![errors](https://user-images.githubusercontent.com/9988184/61962867-6b496880-afc2-11e9-9354-00d167b614a7.png)

**Comment by QwindorRousseau** [comment]
more than likely we are going to have to force the module loading order via code.

**Comment by DazedxJoker** [comment]
It might just need to be attached to the svof system loaded event

**Comment by DazedxJoker** [comment]
I looked at it, not the case. Might want to look into adding something into the loader to make all addons have a priority of 1.

**Comment by QwindorRousseau** [comment]
I know @vadi2 send me the function that can do that so I will take a look at it later and put in a PR on that once I figure out what needs to be done.

**Comment by QwindorRousseau** [comment]
will be fixed one #466 is approved and merged
