### ISSUE TITLE
Selfishness toggle broken when changing to dragon

### ISSUE THREAD

**Issue by druque** [svof/svof#467]
On the in-client branch, the selfishness toggle 'sl' no long works after turning to dragon from lesser. Going back to lesser it is still broken. vkeep selfishness doesn't work either. Other keepups are **not** affected. Log below.

https://ada-young.appspot.com/pastebin/cXO3Raiu

**Comment by QwindorRousseau** [comment]
once selfishness is set to serverside handling it tends to mess up and has always done that because severside does not handle it that well and the system was never coded to have it handle it as it would require resetting selfishness to ignore then forcing generosity and then vice versa. Its why it never gets set as a defences priority on serverside by svo and svo auto correctes itself to handle it on its own when it isnt set to a serverside defence priority.

**Comment by druque** [comment]
If I turn off serverside curing 'tf ss' the problem is still there. Changing curing profile doesn't help.

**Comment by druque** [comment]
In the debug log, there are multiple triggers matching the generosity line, where in regular (not in-client) svof, there is only one trigger.

> 
> Trigger name=2923(A feeling of generosity spreads throughout you.) matched.
> LUA OK: script 2923 (Trigger2923) ran without errors
> Trigger name=12349(A feeling of generosity spreads throughout you.) matched.
> LUA OK: script 12349 (Trigger12349) ran without errors
> Trigger name=19042(A feeling of generosity spreads throughout you.) matched.
> LUA OK: script 19042 (Trigger19042) ran without errors
> Trigger name=20072(A feeling of generosity spreads throughout you.) matched.
> LUA OK: script 20072 (Trigger20072) ran without errors
> Trigger name=22847(A feeling of generosity spreads throughout you.) matched.
> LUA OK: script 22847 (Trigger22847) ran without errors

These extra triggers come from changing to dragon. On a fresh load, there is only one trigger.

**Comment by QwindorRousseau** [comment]
in the current official release there is a lot of code that you cannot see due to it being within lua files where the system references it. We will look into it. For now you can just restart mudlet and it should fix itself.

**Comment by sheepdog-mcfry** [comment]
#475  is opened as we have issues with a lot of defences on system reload
