### ISSUE TITLE
Updater needs to be changed

### ISSUE THREAD

**Issue by QwindorRousseau** [svof/svof#473]
With the system being changed to use the module manager now we need to look at the updater and figure out how to get the updates to be done via the module manager. With this it might be slightly complicated as we need to figure out if we are going to make load into the profile folder like before or just have it update where they currently have the files saved and are using them from in case they are loading them from a dropbox folder for syncing like I currently do to keep my other scripts backed up and updated in case I have another hard drive crash. Just something to think about and get implemented before we do the official release.

**Comment by vadi2** [comment]
I've done started work on this - see functions that can install the system from a zip. This was so the updater can work as before: download the zip and install it.

**Comment by PhoenixCodes** [comment]
Did the old updater require a Mudlet reboot after installing updates?
