### ISSUE TITLE
Dying in the Arena bugs defenses

### ISSUE THREAD

**Issue by impuxi** [svof/svof#479]
If I die in the arena, I basically have to reboot Mudlet all together to get the defenses to work properly again.

https://ada-young.appspot.com/pastebin/zJtU5ogh

**Comment by DazedxJoker** [comment]
I think this might be caused by a lack of actions in the dictionary.

**Comment by impuxi** [comment]
More logs

Another death in the arena: https://ada-young.appspot.com/pastebin/1SfnCI1w

Dragonform to Lesserform after dying: https://ada-young.appspot.com/pastebin/THGi5V6F
