### ISSUE TITLE
Pressure Tracking

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#481]
From my understanding, pressure works similarly to old school humours.

Airlord can raise the level of pressure. If they reach 6 levels they can insta-kill you.

Manaleech, disloyalty, and deadening afflictions will increase the pressure levels that they can give you at once at a max of two. So, if you have none of those afflictions the air lord can raise your pressure level +1, if you have 1 on those afflictions pressure goes up +2, if you have 2 of those afflictions +3. That is the max.

We should be able to look at #447, for how old humour tracking was handled for Alchemist to potentially replicate it.

Puxi grabbed these lines for me, in case they are needed: 

Diag for Pressure: ^the pressure surrounding you is(.*)$

Cured 1 Pressure: As the pressure around you normalises somewhat, your breath is torn from your lungs.
Pressure Cured: The oppressive pressure weighing down on you lifts.

Pressure added: points an imperious finger at you, a wall of air manifesting beneath you and sending you streaking upwards.

Instakill start: ^As the dark intent of (\w+) falls upon you, you feel the air surrounding you begin to thrum with tension.$

**Comment by antar5** [comment]
I cannot provide the lines right now, but some clarifications that I hope helps:

The pressure diag line has a specific line for each level up to 6. 6 and higher shares the same diagnose line

The pressure added line is incorrect (that is updraft, which is irrelevant for counting pressure). The correct pressure given line is actually the instakill line given in the OP. This scales in giving pressure as mentioned above.

You will also need to add the tension line, which gives tension and 1 pressure. Tension always gives one pressure - it does not scale on smoke affs like giving pressure directly does.
