### ISSUE TITLE
@kai showing up when in other classes besides Monk

### ISSUE THREAD

**Issue by impuxi** [svof/svof#486]
Issue: It shows in prompt as "@kai" rather than "".

Example: 
6729h [89%] 99%m 100%w 94%e @kaik cdbk|ex (23:58:49.864)-  

Script: 'Custom prompt' line 132ish

Other Info: Sidhe from Discord thought this could be causing it: I'm going to guess the first if needs to be removed, so cpp.compute_kai will always exist. I think it's showing @kai because it's trying to reference the tag's linked function, not finding it, then shrugging and assuming it's raw text you wanted.

Potentially effecting other class specific prompt functions?

**Comment by vadi2** [comment]
It's intended, because you're not a Monk so you don't have access to those functions? Change your custom prompt not to show kai.

This could be improved but it's not a bug.
