### ISSUE TITLE
Diag looping bug

### ISSUE THREAD

**Issue by antar5** [svof/svof#499]
Ran into the diagnose bug, where the system loops diagnose (and only restarting seems to deal with this). The two occasions I've had it occur were both after I recently starbursted and manually diagnosed on an unknown aff I received afterwards - it starts looping diagnose then. Hope that helps in tracking down the issue. I've a log of this, but it shows little. The first diagnose I sent myself, the ones that followed were being looped by the system (I cut the log short, since it was just looping diagnose at that point): https://ada-young.appspot.com/pastebin/baYPLLz1

**Comment by sheepdog-mcfry** [comment]
I am struggling to replicate this. If you can get a surefire way to replicate this that would be great. Are you on the latest version of the in-client-svof branch

**Comment by DazedxJoker** [comment]
Lose to someone in the arena, when you get revived outside. Use 'dv', that should replicate it.

**Comment by DazedxJoker** [comment]
After some initial testing, it looks like the svo.actions table isn't being populated which is resulting in this looping.

**Comment by DazedxJoker** [comment]
![image](https://user-images.githubusercontent.com/14912622/64221237-1db1fc80-ce9a-11e9-9915-34400b1d5c45.png)

Also, since I'm good a breaking things. This might be relevant.

**Comment by DazedxJoker** [comment]
Okay, in order to replicate the diag looping bug without dying. 
Simply: vlua svo.actions = svo.pl.OrderedMap()


![image](https://user-images.githubusercontent.com/14912622/64480457-e3947380-d195-11e9-80ea-30809c13de45.png)
