### ISSUE TITLE
Enable automatic updates

### ISSUE THREAD

**Issue by vadi2** [svof/svof#5]
Enable automatic updates from Github like Svo used to have them before. Automatic updates are essential, as updating manually makes people lag behind.

**Comment by bunster** [comment]
We could put a *version* file in and then update it via the same way by downloading the raw link?

https://raw.githubusercontent.com/svof/svof/master/version

**Comment by vadi2** [comment]
Yep. Needs to be an http link though as only Mudlet 3.0 supports https ones.

**Comment by Seifur** [comment]
We could embed a luacurl library and use that instead of downloadFile. You only have to download this page (https://api.github.com/repos/svof/svof/releases/latest) and parse it for the tag and file path.

**Comment by Seifur** [comment]
Would need to be hosted elsewhere. Github only serves https. Otherwise we could just parse this page: https://api.github.com/repos/svof/svof/releases/latest

**Comment by pathurs** [comment]
I can provide my website to hold each version, would that suit?

**Comment by keneanung** [comment]
Dochitha set up an AWS instance just today. We're planning an scp deployment here.

**Comment by gymosphere** [comment]
Yes I setup an instance, basically dedicated to just serve updates of SVO, won't be using the instance for anything else. Let me know if it will be used, or @pathurs we can discuss ingame. I am Dochitha ingame.

**Comment by keneanung** [comment]
Will be fixed with next release
