### ISSUE TITLE
Refiller doesn't detect transcendent in Remedies

### ISSUE THREAD

**Issue by slester** [svof/svof#50]
Despite having transcendent remedies, the refiller still tries to put 5 pours instead of 4 into each vial, which means I have to refill by hand (I get the "that would overflow your container" error).

**Comment by vadi2** [comment]
@alex-d-schroder want to have a look?

**Comment by alex-d-schroder** [comment]
I'll go through and figure out how it broke. It might not be until tomorrow (Sept/3/15) that I'll have the time to get a fix in.
