### ISSUE TITLE
Issues when diagnosing with Psion unweaving affs on you

### ISSUE THREAD

**Issue by Taryius** [svof/svof#510]
https://ada-young.appspot.com/pastebin/4wj_Dv-e

Unweaving affs get added to svo's prompt aff tags when received, but if I had to guess their diagnose lines aren't properly added as they get wiped from svo/the prompt when you diagnose with them.

**Comment by K1ngSpad3z** [comment]
Thanks! Seems like they are missing from the diag trigger. Will get those fixed
