### ISSUE TITLE
Defup Spam

### ISSUE THREAD

**Issue by CsmithGames** [svof/svof#519]
It broked.

https://ada-young.appspot.com/pastebin/GhnuS5XI

**Comment by ndsamuelson** [comment]
Care to be a little more specific on what exactly is borked? aside from perhaps lots of bisemutum. did you try telling the system you have ThirdEye in your skills? I can't remember if that's one of the ones you have to tell it specifically or not. Thanks in advance!

**Comment by QwindorRousseau** [comment]
yes you do have to tell the system that you have the mindseye skill or not
