### ISSUE TITLE
Humours and Fractures

### ISSUE THREAD

**Issue by impuxi** [svof/svof#525]
Fractures and Humours currently aren't being tracked correctly. Svof seems to lose count or not count right.

**Comment by vadi2** [comment]
Would you mind providing something solid to look at?

**Comment by vadi2** [comment]
Thx!

**Comment by impuxi** [comment]
I will see if Iakimen and I can get some logs.

**Comment by K1ngSpad3z** [comment]
Achaea pushed an update today on gmcp calling that correctly tracks applications and cures of these things. Since we already had logic in the system for blackout, I am going to remove this error. After some testing everything seems to count properly now
