### ISSUE TITLE
Viridian Defup

### ISSUE THREAD

**Issue by Sharpfangjr** [svof/svof#531]
This seems to happen randomly to me. I have only one class and using the client-side version. The system doesn't always automatically unpause when Viridian is complete during vdefs basic. I've only tested a few times with vdefs combat, but I haven't had an issue yet.

**Comment by DazedxJoker** [comment]
Can we get a log of it happening where you have vconfig log echo on? And a log of it not happening?

**Comment by Sharpfangjr** [comment]
https://pastebin.com/gbrirW5w

That's with it working properly.

**Comment by Sharpfangjr** [comment]
https://pastebin.com/ZDitn1mu

Log of it not unpausing automatically. I had to manually enter pp.

**Comment by PhoenixCodes** [comment]
Is this still an issue @Sharpfangjr?
