### ISSUE TITLE
Constant errors when fighting in blackout

### ISSUE THREAD

**Issue by zakman4466** [svof/svof#532]
Svof34 installed, fighting in dragon. As soon as I get caught in blackout, it starts throwing the following error:

The problem was: prompt vitals function failed - (...rd/.config/mudlet/profiles/Achaea/Runewarden 
svo/svo:22212: attempt to perform arithmetic on field 'maxhealth' (a nil value)). Maybe the system 
isn't installed yet?

As soon as blackout ends, it stops throwing the error. Running mudlet 4.2.1 if it makes a difference.

**Comment by K1ngSpad3z** [comment]
The eroor is prompting from the.class based system. That system is no longer supported. Can you confirm this is not the beta?

**Comment by zakman4466** [comment]
I don't think so, I've installed version 34 straight from the official website/links. Unless that is somehow the beta? Is there a command I can type while in mudlet that will show the version?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by QwindorRousseau** [comment]
version 34 is the current official release. you have to go to the in client branch to download it there and install it the way we said to do it in the forums and the in game svo clan
