### ISSUE TITLE
Remove leading `> ` from qw alias output 

### ISSUE THREAD

**Issue by PhoenixCodes** [svof/svof#560]
The leading `> ` prior to the qw output is unnecessary and kind of annoying. Would be great to remove it!

**Comment by ndsamuelson** [comment]
There's another issue with that trigger too, but I'm not sure if thats because I'm using the beta or what, I'll get further info later and comment again with details if I can pin it down.

**Comment by QwindorRousseau** [comment]
the only issue I know of with it as of current is with MXP turned on. For some reason with that format mudlet does not like it and will set everyone to rogue and IIRC there wasn't much we could do about it right now

**Comment by ndsamuelson** [comment]
the issue I ran into was that the very last line in the qw trigger before the prompt trigger where it has the regex for (I'm not at home so I'm gonna get this wrong) ^(?:Plus another (\d+) adventurers you cannot fully sense \(\d+ total\)\.|\(\d+ total\)\.)$ 

For some reason when only the second option is present, the only way I could get it to fire properly was to remove the ^$ and essentially just remove the first case from the equation, but I only have issues on one of my profiles, But did think it was worth mentioning in case there's a better way to Regex that all out.

**Comment by QwindorRousseau** [comment]
Yea it was a change from when they changed the gem of cloaking and I fixes that with a trigger because the previous one didnt have the portion for when there were no hidden people on the QW list. It is not in the current version but is in the beta.

**Comment by PhoenixCodes** [comment]
Found the reason for this `>` char. It's actually put in as a kludge, because someone didn't understand that selectString(name,num) can return a '0' when it finds the name at the start of a line - first char is at position 0, of course. So they added a char so that the first char of the first name would be at 1. "if selectString(name,1) >0" would be true for the first name. This made me cringe. 

Fixing it is as simple as removing the kludge and changing that to >= 0, though I don't know why they're testing at all... but I trust there's a good reason.
