### ISSUE TITLE
@dl_prompttag and @ml_prompttag not working in multiclass

### ISSUE THREAD

**Issue by Sephem** [svof/svof#562]
I have installed the multiclass beta and the @dl_prompttag and @ml_prompttag do not work anymore

**Comment by PhoenixCodes** [comment]
Can you please tell us what those prompttags were supposed to show? Are these created by something in your system or by Svo itself?

**Comment by PhoenixCodes** [comment]
After further inquiry, these are limbcounter tags that do not exist now... please use the proper tags for the limbcounter as currently implemented in the client-side documentation.
