### ISSUE TITLE
Remove inker module 

### ISSUE THREAD

**Issue by PhoenixCodes** [svof/svof#578]
There is no reason for the inker module - inks are now drawn from the rift directly, and server autoselects a location if it isnt specified. And the inker is broken anyhow.

**Comment by PhoenixCodes** [comment]
I'd say add an inking pauser/unpauser to the main  and let the server do the hard work

**Comment by TheLastDarkthorne** [comment]
Yeah. The inker is unnecessary, at least keep the batch inking and as you said devise a way to unpause and pause or cancel the batch inking.
Also does the server automatically touches inks? If it doesn't it will be good to have a trigger for it to auto touch inks after inking

**Comment by PhoenixCodes** [comment]
Serverside does not auto-touch (tested with moss). Currently, the do-queue can be utilized for inking in batches... I think if we make an inking alias that will batch inks and touching properly in the do queue, plus unpause... that's all that is needed.

**Comment by ndsamuelson** [comment]
for the #329 version, you can just delete the xml for the inker and it wont load it anymore. I had to do that for the inker and the refiller because it was breaking all over because I have my own coded. Just sayin

**Comment by PhoenixCodes** [comment]
Issue resolved with PR #670, please report any issues you are having with the new inker module instead of just deleting it entirely now!
