### ISSUE TITLE
Fix afflictions tracking based on the new server GMCP fixes

### ISSUE THREAD

**Issue by TheLastDarkthorne** [svof/svof#579]
So the guys in Achaea decided to fix how GMCP affliction info is delivered specially on stacking affs. Have no idea what exactly that got fixed, however that's causing a few issues like svof not properly  tracking the cures for some of these affs right even though they were cured by server-side (an example is when a denizen deliver multiple afflictions at once). This should be fixed. Also recommend test if the system is properly tracking affs too after the changes and also if the curing is working client-side.

**Comment by PhoenixCodes** [comment]
I believe that this was or is being handled by @DazedxJoker and/or @K1ngSpad3z

**Comment by PhoenixCodes** [comment]
Ok, or not. @TheLastDarkthorne, can you give an example of somewhere/somehow that this can be replicated so we can track down precisely what's going wrong and fix it?

**Comment by K1ngSpad3z** [comment]
svo already was tracking gmcp changes for afflictions. If anything the update to gmcp tracking only helped svo determine which ones were gained and lost. There should be no changes on our side, unless you can provide a log of something specifically messing up and we can take a look at it @TheLastDarkthorne

**Comment by TheLastDarkthorne** [comment]
Yeah, it happened to me that the svof didn't properly tracked the cure of some afflictions when I was fighting a denizen. I can't find the log of that though :( 
I will pay attention if it ever happens again, maybe it was just a glitch or whatever and I'm getting paranoid lol

**Comment by PhoenixCodes** [comment]
Please let us know if this ends up being an issue again and if there is a sure way to duplicate it. Thanks!
