### ISSUE TITLE
Psion Comprehend defence is not registering

### ISSUE THREAD

**Issue by seriley** [svof/svof#583]
No check box when DEF.
VDEFS BASIC will keep trying to set it and Achaea complains it is already set

**Comment by seriley** [comment]
![image](https://user-images.githubusercontent.com/2272227/72297866-b65b4480-3611-11ea-8b86-d6afe8fe21bb.png)
When I try to set the Comprehend defense a second time, Achaea gives me this message:
"You are already directing your vast intellect to comprehending foreign speech patterns."

**Comment by DazedxJoker** [comment]
Probably need the line from DEF saying it's up. Also, a log of it spamming comprehend would be useful.

**Comment by PhoenixCodes** [comment]
If you don't mind putting it up, then pressing the bomb in the bottom right, and then checking DEF, that would be great.

Also, what DK said. Thanks in advance!

**Comment by seriley** [comment]
![image](https://user-images.githubusercontent.com/2272227/72463810-f3961280-3788-11ea-98c1-03553f3b89e7.png)
I clicked on Emergency stop on timers triggers
Executed psi comprehend
Executed def
Clicked off Emergency stop on timers triggers
Executed def
Executed psi comprehend
