### ISSUE TITLE
Add moss tattoo defup/keepup

### ISSUE THREAD

**Issue by vadi2** [svof/svof#6]

**Comment by jgh713** [comment]
How would fading be handled? Just warn the user when it fades? Warn every few minutes (interval configurable?)? Perhaps auto-ink if deffing up, or warn if it fades on keepup? Or only allow defup?

**Comment by QwindorRousseau** [comment]
@vadi2 do you think we should still do this and expand to include like the megalith, boar, ox, and moon or close it for now and if people want it they can bring it up again?

**Comment by vadi2** [comment]
Yeah, lets do the latter.
