### ISSUE TITLE
Inline ASCII bars crash

### ISSUE THREAD

**Issue by wysvaine** [svof/svof#603]
The trigger for bar health on assess is susceptible to illusions - an illusion of 99999/1 health or similar will cause mudlet to crash as it tries to generate an impossibly large bar.

![image](https://user-images.githubusercontent.com/62292551/76858999-d89a5a00-682e-11ea-837a-bafe0baa6b0b.png)

[inline bar health xml.txt](https://github.com/svof/svof/files/4343775/inline.bar.health.xml.txt)

**Comment by ndsamuelson** [comment]
Dang why did I never try that!? Good show. 👍 @wysvaine

**Comment by vadi2** [comment]
The trigger is off by default in Svof, thankfully :smile:
