### ISSUE TITLE
VCONFIG SINGLEPROMPT

### ISSUE THREAD

**Issue by BurningWhiteRose** [svof/svof#607]
Using VCONFIG SINGLEPROMPT itself works, but when activated it makes my prompt go on endlessly. I've attempted resolving by resetting the Achaea side prompt, making my SVO custom prompt the default or something shorter, and then using only health but it makes it loop endlessly. 

I've also attempted reinstalling SVO, trying on new profiles, etc.

How to recreate the bug:
Log in
Be alive
vconfig singleprompt

Specs:
Latest Version of SVO
Paladin
Serverside On

**Comment by DazedxJoker** [comment]
Inconsistent use of a mini console name to clear it causes it to not be cleared.

Just need to replace most instances that are clearWindow("bottomprompt") with svo.bottomprompt:clear()
