### ISSUE TITLE
Monk Limbcount

### ISSUE THREAD

**Issue by VinceresEbonheart** [svof/svof#610]
I had updated to the new in-client, and my Monk Limbcount doesn't appear to be working anymore. In previous versions, it used svo.ml_hit to track monk limb damage and used the @ml_prompttag for display. I know there was a previous ticket that said the prompttags were updated and to use the new updated ones.

I'm currently using the @lc_prompttag which does show on my display, but svo doesn't seem to be tracking any monk limb hits. Looking through the code, my monk limb tracker triggers still seem to be using svo.ml_hit -- when I search for the corresponding function, the function doesn't exist. I'm assuming it needs the updated to use the lc_hit function, but when I tried to change the triggers to use it, it didn't work correctly.

**Comment by vadi2** [comment]
I think @K1ngSpad3z merged them all into one limbcounter - maybe there's a different tag now. Do the docs say anything about this?

**Comment by VinceresEbonheart** [comment]
I thought that was the case as well. Using @lc_prompttag works fine with my magi and druid, but it doesn't look like monk (tekura) was updated? Shikudo code looks like it would work fine, but I'm not shikudo and can't test that.  I tried looking in the new documentation, but I didn't see anything related to the limbcounter.

**Comment by VinceresEbonheart** [comment]
Tekura AXK still needs to  be updated to use lc_hit instead of ml_hit
