### ISSUE TITLE
Earthlord Limb Counter

### ISSUE THREAD

**Issue by VinceresEbonheart** [svof/svof#622]
I may be incorrect with my logic, but it seems the earth lord limb counter isn't calculating shaping properly. 

When someone powderises a limb, the amount of limb damage is based on how many levels of shaping the person has prior to the attack. For example, if I have level 1 shaping, it should do 1 limb damage, then elevate my shaping to level 2. 

However, it looks like the limb counter is elevating the level of shaping PRIOR to assessing how much limb damage the powderise is doing. For example, if I have level 3 shaping and I powderise a limb, it _should_ elevate the limb count by 1 (since I only had level 3 shaping when I attacked). Instead, what it's doing is raising my level of shaping to 4 which would then mean that it's saying my powderise is elevating by 2 hits, which is not correct.

This is what it looks like in the code:

local shaping = string.match(gmcp.Char.Vitals.charstats[3], "%d+")
shaping = tonumber(shaping)
if shaping == 4 then
	svo.lc_hit(matches[3], matches[2], 2)
elseif shaping <= 3 then
	svo.lc_hit(matches[3], matches[2], 1)
end

Instead I think it should be rearranged to look like this:

if shaping == nil or shaping <= 3 then
  svo.lc_hit(matches[3], matches[2], 1)
elseif shaping == 4 then
  svo.lc_hit(matches[3], matches[2], 2)
end
shaping = string.match(gmcp.Char.Vitals.charstats[3], "%d+")
shaping = tonumber(shaping)

Also, it looks like SVO says it should break with 6 hits, but earth lord breaks at 5 (at least when I do it without artefacts).

**Comment by VinceresEbonheart** [comment]
Only problem I can foresee with the way I have it is that shaping is also increased by Pulverise as well. So a separate trigger might need to be made to ensure it tracks shaping that way too.  "You rain a flurry of blows down upon \w+ with your stone fists."

**Comment by VinceresEbonheart** [comment]
No stale.

**Comment by K1ngSpad3z** [comment]
Won't need the trigger for Pulverise. Going to have to add in a variable to track shaping on gmcp output and use the above trigger like that. the way the limbcounter works is that it does the calculations on next prompt, so it won't need to update the shaping count after the hit is sent through. I will take a look at this when applying a few other changes @VinceresEbonheart

**Comment by VinceresEbonheart** [comment]
Still doesn't work correctly after the fix. The way shaping works.  You start at 0 shaping. You attack. Deal 1 hit damage. Increases shaping to 1. -- hit. Deals 1 damage. Increases to level 2. -- hit. Deals 1 damage. Increases to level 3. -- hit deals 1 damage. Increases to level 4. -- hit. Deals 2 damage. Stay at level 4.

The code is not checking your shaping level at the appropriate time. The way it currently coded -- is that it triggers UPON your attack. So you check shaping level, then it increases hit by 1 or 2. But by the time your attack is trigger, Achaea has already increases your shaping level. ---- So If I'm at level 3 shaping. I attack -- triggered off my attack to check shaping (which shows as level 4 because I have attacked)...then it says I dealt 2 damage, which is not right...since my attack was initiated when I had 3 shaping and it should only deal 1 damage.
