### ISSUE TITLE
AirLord Pressure and Afflictions 

### ISSUE THREAD

**Issue by VinceresEbonheart** [svof/svof#626]
Old Issue 508 and some further back as well 481, I think. SVO is not tracking afflictions given by airlord, including manaleech, tension, disloyalty, pressure, etc. There are no corresponding triggers in the most updated version.  Below is what I have as far as triggers are concerned if this helps:

Pressure
=======
^As the dark intent of (\w+) falls upon you, you feel the air surrounding you begin to thrum with tension.$

This will elevate pressure by 1, unless you have certain afflictions. If you have 1 of either manaleech, disloyalty, or deadening, it will elevate pressure by 2. If you have at least 2 of those afflictions, it will elevate pressure by 3. 

Pressure Diag Lines:
=======
the pressure surrounding you is slightly elevated.     ---- 1 pressure
the pressure surrounding you is elevated.                  ---  2 pressure
the pressure surrounding you is moderately elevated. -   3 pressure
the pressure surrounding you is severely elevated.     -    4 pressure
the pressure surrounding you is extremely elevated.  -    5 pressure
the pressure surrounding you is terminally elevated.   -  6 pressure

Pressure Cure/Decrease
======
^As the pressure around you normalises somewhat, your breath is torn from your lungs.$ --- decreases pressure by 1

^The oppressive pressure weighing down on you lifts.$ --- Pressure down to 0. 

Tension
=======
^You feel the air suddenly growing thick around you, your breaths becoming cloying.$

Gives tension affliction and will elevate pressure by 1 if you have pressure, otherwise will give pressure.

Manaleech
=======
^(\w+) casts a hand out in your direction, an icy zephyr descending upon you to tear your fortitude away.$

^A second rush of icy wind sweeps over you, leeching away your strength.$ --- this is a relapse of manaleech

Disloyalty
=======
^A howling wind sweeps over you, its terrible power scouring flesh from bone and leaving your face a bloody ruin by the will of (\w+).$

Deadening
=======
^(\w+) clenches a hand into a fist, a sudden force locking closed about your throat and constricting your airflow.$

^You feel a sudden pressure close about your throat, cutting off your ability to breathe and making your mind grow foggy.$

^As your mental fortitude continues to slip away, your mind seems to become sluggish and unresponsive.$

Blackout
=======
^Your mind goes blank, your thoughts slipping away like so much smoke on the wind.$

Disrupt
=======
^Your head swims and you feel your grasp of your mental facalties slipping away.$ ---- (not sure if the spelling of facalties is a serverside typo...submitted a typo so this may change)

Stun
=======
^The pain radiating from your face becomes too much to bear.$

I'm probably missing the trigger lines from some of the relapsing abilities. Also missing the manaleech caused by Duress Gale.

**Comment by K1ngSpad3z** [comment]
The system has gmcp tracking in place already, to account for a majority of these afflictions already. Class afflictions such as tension are already tracked by the system. The only thing not present is pressure currently. I will add some triggers to account for diagnosing and blackout, as well as add proper tracking for Pressure
