### ISSUE TITLE
Gem of Reincarnation

### ISSUE THREAD

**Issue by VinceresEbonheart** [svof/svof#627]
So I used a gem of reincarnation to resurrect myself when I was dead.

And the system just keeps spamming this:

(svof): Welcome back to life! System unpaused.
curing on

This has happened a few times, and from what I recall, I only have this problem when I died in dragonform and reincarnate into dwarf or something else. 

VRESET doesn't work. I usually end up needing to close out mudlet and re-login.

**Comment by K1ngSpad3z** [comment]
This might just be as simple as triggering the gem reincarnation line to force a class change. @VinceresEbonheart can you provide the line you get after using it?

**Comment by DazedxJoker** [comment]
Here's a log of it from Aegoth: https://ada-young.com/pastebin/Doj0Vx41

I couldn't replicate it.

**Comment by PhoenixCodes** [comment]
@DazedxJoker did you try the dragon into lesser?

**Comment by VinceresEbonheart** [comment]
I just tried to replicate it again, but was not able to replicate. I heartstopped in dragon. Reincarnated into dwarf and it seemed to work fine.

**Comment by PhoenixCodes** [comment]
We'll have to keep an eye on this.
