### ISSUE TITLE
Serverside Alises are now capped at 10 commands

### ISSUE THREAD

**Issue by K1ngSpad3z** [svof/svof#629]
Achaea pushed an update recently that capped serverside aliases to 10 commands instead of the original 20, as seen in Announce 5250. They also updated the CURING PRIORITY and CURING DEFENCE PRIORITY commands to allow multiple changes to each number

This will mainly effect curing priority changes that the system sets on re initialization through the alias it creates.

With these changes the serverside alias can be changed from:

`curing priority defence fangbarrier reset/curing priority defence third eyereset`

to:

`curing priority defence fangbarrier reset thirdeye reset`

Allowing us to send all the changes in afflictions and defences in a single command

https://cdn.discordapp.com/attachments/578659570973409355/744630083167322222/unknown.png

https://cdn.discordapp.com/attachments/578659570973409355/744630339682435173/unknown.png

**Comment by K1ngSpad3z** [comment]
Leaving this open as an enhancement as the code Ada provided helped cap the system commands for now

**Comment by ndsamuelson** [comment]
This has been resolved as far as I'm aware. Could probably close.
