### ISSUE TITLE
Druid Wyvern Flame

### ISSUE THREAD

**Issue by VinceresEbonheart** [svof/svof#636]
System is not recognising that I already have wyvern flame and keeps trying to summon flame, specifically only when I use the _ignite_ ability to jump start the flame rather than _summon flame_

https://ada-young.com/pastebin/44JSt-19

**Comment by DazedxJoker** [comment]
`
  defs_data:set('flame', { type = 'metamorphosis',
    specialskip = function() return not sk.morphsforskill.flame end,
    onenable = function (mode, newdef, whereto, echoback)
      for _, morph in ipairs{'squirrel', 'wildcat', 'wolf', 'turtle', 'jackdaw', 'cheetah', 'owl', 'hyena', 'condor', 'gopher', 'sloth', 'bear', 'nightingale', 'elephant', 'wolverine', 'jaguar', 'eagle', 'gorilla', 'icewyrm', 'hydra'} do
        if morph ~= newdef and svo['def'..whereto][mode][morph] then
          svo['def'..whereto][mode][morph] = false
          if echoback then svo.echof("Removed %s from %s, it's incompatible with %s to have simultaneously up.", morph, whereto, newdef) end
        end
      end

      return true
    end,
    invisibledef = true,
    on = {"You take a deep breath and realise your error - you sputter and engulf yourself in fire!", "You take a deep breath and feel the heat begin to build within you.", "You are ready to breathe yellow fire.", "You are ready to breathe blue fire.","You are ready to breathe white fire.", "With a roar you channel your reserves into your inner flame, instantly summoning forth a raging inferno."},
    offr = [[^You inhale deeply, allowing the raging flames to build up inside you. With an earth-shaking roar, you release a white-hot jet of fire directly at \w+\.$]],
    off = {"A small gout of fire erupts harmlessly from your mouth.", "You take a deep breath and realise your error - you sputter and engulf yourself in fire!", "Unleashing white-hot flames in a reckless burst of fire, you create a roaring inferno about your person.", "Your inner fire does not burn with sufficient intensity, Metamorph.", "You take a deep breath and realise your error - you splutter and engulf yourself in fire!"},
    })
    --Wyvern, Basilisk`

I don't druid, but according to that log did they change the lines for for the blue/white fire. Or is that just a different line?

**Comment by VinceresEbonheart** [comment]
It's a different line for 'ignite'.

Summon Fire: (then goes from yellow, blue, white)
You take a deep breath and feel the heat begin to build within you.

Ignite: (starts at blue and goes to white)
You may now breathe blue fire.
With a roar you channel your reserves into your inner flame, instantly summoning forth a raging
inferno.


If you try to summon flame when you already have a flame or are currently summoning one:

You are already summoning your flame.

**Comment by PhoenixCodes** [comment]
Gonna take a look at this tonight, should be easy to add in those lines. I don't have a druid to test on, @druid will be asking for your help

**Comment by PhoenixCodes** [comment]
Confirmed that this is a bug. None of the 'on' lines seem to be registering correctly, even when adding the line 'You are already summoning your flame.', can't get it to recognize that my flame is, in fact, summoned.

**Comment by PhoenixCodes** [comment]
After fixing the flame colors (which did change, yes), and making sure ignite is correct... `With a roar you channel your reserves into your inner flame, instantly summoning forth a raging inferno.` is still not matching for some reason.

**Comment by PhoenixCodes** [comment]
After flame lines are fixed, tracked this down to anti-illusion - it is disbelieving flame lines unless due to a "summon flame", and I'm not quite sure why. Will investigate more tomorrow!
