### ISSUE TITLE
Fire Lord Ablaze defence

### ISSUE THREAD

**Issue by PhoenixCodes** [svof/svof#638]
ablaze is a defence for fire elementals, provides mild regen. It does not show up on DEF. This defence should be added somehow. 

When on keepup or defup and in the fire elemental class, the aff should be ignored. 

On: You flare your flames, burning ever brighter.
Off: Standard flame affliction cure lines
Continuous message while on: The fires crackling across your primal form bolster your eternal flame.
Syntax: MANIFEST TORCH
Already on: None, allows you to use it when already on.
Balanceful: yes, 2s

**Comment by PhoenixCodes** [comment]
This needs the `invisibledef` flag as it does not show up on def.

**Comment by DazedxJoker** [comment]
Closed #642
