### ISSUE TITLE
Monk Tekura Limbcounter

### ISSUE THREAD

**Issue by VinceresEbonheart** [svof/svof#639]
From what I can gather from the code, when you switch your class to monk, it's supposed to enable to monk tekura triggers, which it does. However, in the script 'svo limbcounter' it looks like it's supposed to spit out an echo and command line to set arm and legdamage...but it doesn't do that. 

It implies you should be able to do 'vconfig legdamage #' or 'vconfig armdamage #' to set the appropriate damage, but it doesn't allow those to go through. So I don't see any option where svo.conf.legdamage or svo.conf.armdamage actually get set, as they don't appear in any other aliases or triggers or scripts.

**Comment by K1ngSpad3z** [comment]
It does not spit out an echo upon class change. Assuming you are in Tekura monk, there will be an option under `vconfig2` that will prompt you with `vconfig (legdamage or armdamage)` and asks you to put in a number. You can also do this manually, and it will update `svo.conf.legdamage` and `svo.conf.armdamage` respectively. The set config code is what creates the option to use vconfig, and there would be no triggers or aliases added to do such. I went in and tested it today and its working as intended

https://cdn.discordapp.com/attachments/578659570973409355/750038884913774662/unknown.png

**Comment by VinceresEbonheart** [comment]
Ok! I’ll try again when I get home. When I tried vconfig armdamage 3, it just give me the list of all different things but wouldn’t set it. But I will try again going by what you had in the screenshot.

**Comment by VinceresEbonheart** [comment]
When I try 'vconfig armdamage 1' or 'vconfig legdamage 1' -- it does not go through. I can make my own alias to set svo.conf.armdamage and svo.conf.legdamage...but the vconfig one doesn't seem to work ? It shows I'm on version 40. Is this the most recent one?

**Comment by VinceresEbonheart** [comment]
As well, another issue I've noticed is that the trigger for AXEKICK is still using the old svo.ml_hit script, which is no longer used. It should be switched to svo.lc_hit like all the other triggers.
