### ISSUE TITLE
Documentation needef for the Defence table flags

### ISSUE THREAD

**Issue by PhoenixCodes** [svof/svof#640]
All flags are boolean unless otherwise noted.

Please help build this list so that we can add it to the documentation properly down the road!

balanceful - indicates the defence uses balance
balanceless - indicates the defence does not use balance 
nodef - indicates the defence is not able to be put up by the user
invisibledef - indicates that despite being a defence, it does not show up on "defences"

**Comment by vadi2** [comment]
If you can find others that are unknown, happy to explain
