### ISSUE TITLE
vkeep insomnia used cohosh with insomnia skill enabled

### ISSUE THREAD

**Issue by slester** [svof/svof#65]
When I logged in (with vkeep insomnia in basic mode):
```
You remove 1 black cohosh, bringing the total in the Rift to 2376.
You eat a black cohosh root.
You suddenly feel incapable of falling asleep.
You rub your hands together greedily.
```

However `relax insomnia` correctly uses `insomnia` to restore it.

**Comment by vadi2** [comment]
That log really doesn't show much - enable viewing system commands, you could have had something else use cohosh.

**Comment by slester** [comment]
Sorry about that!

```
Enter an option or enter your character's name. (+1h, 100.0%, +1m, 100.0%) 
What is your password? 
(outr cohosh|eat cohosh|selfishness)
Password correct. Welcome to Achaea.
(mapper): We're connected to Achaea.

Settings loaded.(diag)
Your last login was from domain:

The vitality of the black boar begins to flow through you.
The light of the moon illuminates you.
Your moss tattoo tingles slightly.
```

**Comment by vadi2** [comment]
Hmm, no insomnia use there... :(

**Comment by jgh713** [comment]
Can't seem to reproduce this at all. Close for now and open another if this starts happening again?

**Comment by keneanung** [comment]
@slester As suggested I'm closing this. If this still happens and you have more info (maybe a longer log with more context), feel free to reopen this.
