### ISSUE TITLE
Echoes are added to a single prompt

### ISSUE THREAD

**Issue by Marmidon** [svof/svof#650]
Issue: When doing a simple echo, with **vconfig singleprompt on**
Example of this happening: (note - if I had \n in echo, then the singleprompt would appear empty).
The easy way to reproduce it was to spam a lot of echoes.
The code that creates this simple echo in example:
echo('COMMAND TO DO - '..command_to_do)
![image](https://user-images.githubusercontent.com/10533234/92946616-e408bf80-f424-11ea-9918-5b7b0681364e.png)

Example of normal singleprompt, how it usually looks:
![image](https://user-images.githubusercontent.com/10533234/92947094-8c1e8880-f425-11ea-81d5-c8025018ea95.png)

**Comment by PhoenixCodes** [comment]
Still an issue
