### ISSUE TITLE
the do queue halts progress in blackout

### ISSUE THREAD

**Issue by DazedxJoker** [svof/svof#653]
Presently: If you have something on Do-Repeat and you enter blackout. It ceases repeating until you get out out of blackout. Also looks like affliction tracking might be a bit wonky in blackout as well.

![image](https://user-images.githubusercontent.com/14912622/93132918-69e66e00-f6a4-11ea-8425-398782b9b2c1.png)

Might be tied into #648

**Comment by awitteio** [comment]
Closed this for now, as the current build is not having any issues with this. Will keep an eye on it though.
