### ISSUE TITLE
Aeon Bug

### ISSUE THREAD

**Issue by VerdellAchaea** [svof/svof#658]
Pastebin log:

https://ada-young.com/pastebin/iCWwGfXE

Svof and Curing seem to be battling to cure aeon properly

**Comment by PhoenixCodes** [comment]
I will personally pay 25 credits to any non-dev that manages to fix this. Devs, this is our job, get on it anyways. You get kudos.

**Comment by DazedxJoker** [comment]
Relevant information, the system doesn't seem to enter into Slow curing mode when it is afflicted. I thought this was partially related to our changes to signals.gmcpcharafflictionsadd to add affliction via gmcp.
