### ISSUE TITLE
Double Impale not writhing

### ISSUE THREAD

**Issue by RefundMan** [svof/svof#680]
Was sparring Caladbolg and he noticed I wasn't writhing when he impaled me sometimes so we tested briefly outside the arena and the following happened:

![image](https://user-images.githubusercontent.com/73865186/97945685-36e06280-1d56-11eb-9d5e-3b8f6b9e139c.png)

I feel like it's waiting on a balance that doesn't exist. Anti-illusion is off and it's able to be replicated by back to back impaling.

**Comment by PhoenixCodes** [comment]
![98051990-0d314500-1e03-11eb-8060-78937bdcdaf3](https://user-images.githubusercontent.com/15858451/98052435-d99eec80-1dfb-11eb-867a-b71267319f51.png)

**Comment by DazedxJoker** [comment]
![image](https://user-images.githubusercontent.com/14912622/98067991-cfdfae00-1e28-11eb-8739-2b59105bc512.png)

**Comment by DazedxJoker** [comment]
So, I changed the customwait in the curingimpale.waitingfor dict entry from 6 to 2 and it seems to handle better

![image](https://user-images.githubusercontent.com/14912622/98068602-7e382300-1e2a-11eb-81ca-1ff3d56fdb7f.png)

However, I have no idea if this will poorly effect other impaling techniques.

**Comment by PhoenixCodes** [comment]
Writhe changes in-game mean we need to take a new look at if this is even still an issue, and whether the changes mean we should be handling writhe logic more directly instead of with timers.
