### ISSUE TITLE
Occasional missing aliases or scripts after crash

### ISSUE THREAD

**Issue by ndsamuelson** [svof/svof#684]
I've heard and experienced myself an issue after certain crash scenarios where upon reloading mudlet and such, your aliases look like they're there but do not function. It can be resolved by forcing the in-client version to download again, and then the missing script issues seem to resolve.

Not so much an svof issue as a mudlet one, but if someone wants to tackle a solution or put it someplace informative, go nuts!

**Comment by QwindorRousseau** [comment]
@vadi2 any idea?

**Comment by PhoenixCodes** [comment]
I dont think there's anything in svo that could cause this. Believe if its still happening it needs to be reported to Mudlet. Would vote for closing it

**Comment by QwindorRousseau** [comment]
@PhoenixCodes yea thats why i tagged vadi about it. Figured he would have better insight

**Comment by vadi2** [comment]
It would be a Mudlet issue, but need more information - @ndsamuelson can you make a video of what happens after?

**Comment by ndsamuelson** [comment]
@vadi2 Unfortunately I've not been able to recreate, this was one that I helped someone else with, and the resolution that they provided was just as I described above. I just wanted to make sure it was at least glanced at in case it came up more frequently.
