### ISSUE TITLE
remove riding as a keepup in elemental lord, as well as blocking.

### ISSUE THREAD

**Issue by ndsamuelson** [svof/svof#686]
since elemental lords cannot mount steeds or block **(I know at least waterlord can't, not sure on the others)** this ends up looping over and over if you add to keepup accidentally or whatever the case may be.

**Comment by QwindorRousseau** [comment]
Pretty sure you can block as earth lord but i need to verify when i get in game again

**Comment by ndsamuelson** [comment]
yeah I mean you can hide the defs I suppose, I just mean as far as polish goes for the new user and QoL overall. Nothing ***earth-shattering*** heh.  Just checking things off my list:
- [x] Mention all the things
- [x] Nail it.
- [ ] Break more things.

**Comment by QwindorRousseau** [comment]
Confirming that Earth Lord does have the ability to block for reference on whoever is working on this.
