### ISSUE TITLE
OLDTS not functioning as intended.

### ISSUE THREAD

**Issue by sdelo1185** [svof/svof#694]
When OLDTS is set to false, it functions correctly by reapplying shield.

When OLDTS is set to true, it still shows TS being toggled, but it will only shield on every other TS command instead of every command.

**Comment by DazedxJoker** [comment]
![image](https://user-images.githubusercontent.com/14912622/99870797-da79a180-2ba3-11eb-829d-d7a332c81360.png)

Looks like it is working as intended, are you sure you're on the most updated version?

**Comment by PhoenixCodes** [comment]
@DazedxJoker I nly see one running of `ts` in your test screenshot. P
