### ISSUE TITLE
Tattoo Inker does not accept a limb argument 

### ISSUE THREAD

**Issue by sdelo1185** [svof/svof#695]
Does not work when trying to ink tattoos. Have to turn off the tattooing alias and manually tattoo.

**Comment by PhoenixCodes** [comment]
Can you show a log of this? The tattooer was recently overhauled. As far as I know, it only breaks if someone else in the room has a failed tattoo ink at the same time, and that's due to Achaea not showing which tattooist has failed to ink.

**Comment by sdelo1185** [comment]
https://ada-young.com/pastebin/kkybjhjX

**Comment by K1ngSpad3z** [comment]
update to the latest version of the in client system and try it again, I have tried to figure out a way to replicate this error and can't. Its working as intended on my end. (in game do vupdate force to get the latest build for the system)

**Comment by sdelo1185** [comment]
Seems that when i use the new ink alias it works fine if i just do ink (tattoo name)

**Comment by PhoenixCodes** [comment]
oh, I see what happened. You selected a body part. Inker does not support that, but should. I'll mark this as an enhancement request.

**Comment by sdelo1185** [comment]
Does this accept an argument for inking on others?

**Comment by tsartin** [comment]
This can probably be closed.

**Comment by ndsamuelson** [comment]
> This can probably be closed.

Can confirm.
