### ISSUE TITLE
Handle serverside queueing to backstab+illusion at once

### ISSUE THREAD

**Issue by vadi2** [svof/svof#7]
There's an issue in the game where it doesn't separate **Illusion** from a real attack when serverside queueing is used. This makes it real hard for a clientside system (not serverside, because it conveniently ignores all illusions) to detect what was the illusion and what was the real attack, as it's all mushed up in one.

In Lusternia, this was solved by adding a prompt between the detected illusion and the real attack.

I've filed a bug report, but it's not having any traction:

Your bug report #20400 (detail: if you use serverside queueing to backstab and illusion at once, the game does not separate the illusion with a prompt - making it really, really hard to detect if *\* Illusion *\* comes up at any point. Lusternia fixed this issue by forcing a prompt before the illusion) - has been assigned to design category.

**Comment by QwindorRousseau** [comment]
With admin it might be a problem as that is somewhat a strategy serpents can use to confuse a system which sometimes we have to do. But then again it is possible that they may do the same thing as lusternia but it may not come out for a little bit with current events. Might also help to message makarios personally and from what i have seen he will take a took at things like that pretty quickly or at least give you a little bit better response than the bug system does

**Comment by jgh713** [comment]
Needs to be tested to see if this is still the case. Shouldnt really matter (in most cases) with gmcp affs, but worth looking into. If nothing else, force svo to stop recognizing illusions after 2 lines (seeing as they're limited to one newline).

**Comment by QwindorRousseau** [comment]
With the overhaul to illusions awhile back i do not see them being used as much due to the balance cost on them which was the intended purpose. They are more used in a defensive perspective to fool peoples cure tracking.
