### ISSUE TITLE
Vibrato assumes L2 break on every hit.

### ISSUE THREAD

**Issue by Esync7** [svof/svof#704]
Svof believes Vibrato damages an arm to L2 on every hit, despite this not being the case. Either it's triggering twice, from GMCP and then the actual trigger line, or it's simply still written that Vibrato automatically damages any crippled arm to L2. (This used to be true)

![VibratoLog](https://user-images.githubusercontent.com/17302501/100529881-eb7c7100-31a8-11eb-9777-f806bd2f7273.png)

**Comment by PhoenixCodes** [comment]
I find it interesting that curing LV1 doesn't let the system know that LV2 didn't exist after all. Seems like a fixable thing as well?
