### ISSUE TITLE
Nechamandra not tracking shivering/frozen properly

### ISSUE THREAD

**Issue by VinceresEbonheart** [svof/svof#706]
Hello! It appears when using nechamandra bite, it is not properly tracking freezing.

Bite 1 strips caloric. Bite 2 should give shivering, but on bite 2 it's showing that it gives shivering AND frozen, but when you diagnose, you're not frozen. 

The log attached shows it when using nechamandra with druid hydra, but it's the same if I bite myself as a serpent with nechamandra. 

Strangely enough, when I had someone use icewyrm freeze on me, it tracked properly as only being shivering, despite the fact that I cannot find one trigger in there for icewyrm freeze. 

https://ada-young.com/pastebin/pGWdHW9B

**Comment by VinceresEbonheart** [comment]
https://ada-young.com/pastebin/AqTn8NZn - this log shows the icewyrm tracking shivering properly, but there's no trigger in there anywhere for that line. o_o

**Comment by RollanzMushing** [comment]
As far as I can tell, this is caused by ``svo.valid.proper_chill`` adding a layer of cold after the Char.Afflictions.Add GMCP message is processed. Adding the following check to the beginning of the function fixes the problem:
```lua
if not svo.affl.blackout then return end
```
