### ISSUE TITLE
Enchantment script doesn't work with portable ourobori artefact

### ISSUE THREAD

**Issue by VinceresEbonheart** [svof/svof#707]
I purchased the 'a portable paired ourobori' artefact and it doesn't seem compatible with the enchanting script. It doesn't recognize the ourobori in the room.

Artefact isn't typical, since it's considered one object, rather than two separate ouroboros in the room. And the description is different than your standard ouroboros.

**Comment by PhoenixCodes** [comment]
Definitely would be nice to add artefact support to the enchantment script!

**Comment by VinceresEbonheart** [comment]
Nevermind. I am a moron. This work perfectly fine as is if one reads the instructions on how to use the artefact. You need to PLACE OUROBORI in the room, which will drop two beguiling ouroboros in the room which allows the script to work perfectly.
