### ISSUE TITLE
Apostate reporting

### ISSUE THREAD

**Issue by rwt88** [svof/svof#718]
Currently there is a priest report module but none for Apostates. It seems if would be easy to adapt the priest report stuff for Apostate.

Thanks

**Comment by TheLastDarkthorne** [comment]
Could be done! Please, if you are apostate, can you take a look at the priest report triggers and tell me the what are the apostate's and baalzadeen lines for the triggers that are there, like the seek lines, failed seek, etc? Doing so we could make a new one and adapt it

**Comment by rwt88** [comment]
Apostate demon trace:

--trace failed
Your Baalzadeen cannot sense the person you wish to trace.

--trace start
You bid your Baalzadeen to trace the movements of (.+) around the land.

--actual trace message
Your Baalzadeen reports that (\w+)has moved to (.+).

Apostate do not have a demon seek ability

**Comment by TheLastDarkthorne** [comment]
Eeep I was working on this! Sorry sorry sorry... life been crazy.
Bad bot! Don't close it!
