### ISSUE TITLE
Defup not working Propagation Barkskin

### ISSUE THREAD

**Issue by seriley** [svof/svof#73]
I've verified that svo.defdefup.basic.barkskin is true.
When I do VDEFS BASIC, the barkskin defence is not set

**Comment by alex-d-schroder** [comment]
Do me a favor, and close out of Mudlet. Come back in, and def up. When you finish, check to see if you have the defence by typing "DEF". If it's not checked off, immediately do VDEFS BASIC again (do not manually put up barkskin). See if the system puts barkskin up then.

**Comment by seriley** [comment]
I did as you suggested. Bearskin was not put up after I tried VDEFS BASIC the second time. I did VDEFS BASIC, DEF, VDEFS BASIC, DEF.

**Comment by seriley** [comment]
I didn't do anything different, other than misspell 'barkskin' in my last post, and the issue has gone away for me. VDEFS BASIC now brings up the barkskin defence correctly.

For me, this issue is closed.

**Comment by alex-d-schroder** [comment]
It doesn't for me, on a Sylvan I've been testing it on. It's as if the defup sequence gets frozen, and manually putting up barkskin shows the "finished putting up defences" echo. Keep the issue open for now.

**Comment by QwindorRousseau** [comment]
Need to verify if still a issue in the in-client. Tagging it as such for suggested looking into before release.

**Comment by QwindorRousseau** [comment]
i am seeing the lines and the defence in the scripting and this is quite an old issue so closed until it comes up again if there is an issue
