### ISSUE TITLE
SVOF Install  Documentsd

### ISSUE THREAD

**Issue by tsartin** [svof/svof#736]
In the https://svof.github.io/svof/ documentation, there is no mention of how to install the modules.  While this is pretty self-explanatory for regular Mudlet users, it is very confusing to people new to Mudlet and svof.

Something simple along the lines of, 1 download this. 2. unpackage 3. install this file here should be fine.

**Comment by ndsamuelson** [comment]
While I agree it should be in the docs, that very set of instructions can currently be found [here](https://github.com/svof/svof#setup). Good catch.

**Comment by TheLastDarkthorne** [comment]
Oop forgot to mention this issue in the PR but it is fixed now, there is a link to install instructions in the in-client branch readme page now!
