### ISSUE TITLE
Developer readme need to be brought to inclient tree and updated

### ISSUE THREAD

**Issue by TheLastDarkthorne** [svof/svof#746]
Svo is a very big and complex system and many people can get confused where to start adding things and learning the system structure. The Developer Readme on master should be updated to reflect the changes on inclient code structure as well as updating the directions on how and where to add things and how the many functions works as well so that new developers don't get completely lost in the sea of code!

Not the most urgent issue but should be looked at somewhere down the road.

**Comment by tsartin** [comment]
I used your new documentation to add a new affliction. It helped a ton.

**Comment by TheLastDarkthorne** [comment]
I have included the developer readme awhile ago, forgot to close this. Oops!
