### ISSUE TITLE
Shrugging Filling Curing Queue and Not Being Able to Fire

### ISSUE THREAD

**Issue by tsartin** [svof/svof#755]
Shrugging was changed to 'curing queue add' to help with people that queue all their attacks.

It seems like the normal queue always fires before the curing queue so it ends up filling the curing queue with 'shrugging' a ton of times (sometimes maxing it out) and you'll shrug for the next 2 minutes even without afflictions.

The best bet would probably be to figure out how to have shrugging go through even when people are queueing but another option might just be track what has already been queued and not add it again if already there.

**Comment by tsartin** [comment]
Could we have this and other recent stale issues reopened? Thank you

**Comment by keneanung** [comment]
Closed with #769
