### ISSUE TITLE
Add airfisted affliction from blademaster

### ISSUE THREAD

**Issue by tsartin** [svof/svof#765]
airfisted is missing from svof.

Prevents parry.  Might need to be added to parry logic somewhere as well.

It's cured by time. 15 seconds.

Shows in gmcp but also here are the triggers.

Gained:
Moving with unpredictable grace, Hapi sends a dancing blow towards you.
A sudden phantom wind seizes your mind, blurring the world into a shifting sea.

Cured:
Clarity of form returns as the wind plaguing your mind dies down.

**Comment by tsartin** [comment]
Just noticed this might be 'galed' in svof. I'll double check later.

**Comment by keneanung** [comment]
Seems to be already in there, even though the name is different
