### ISSUE TITLE
Paladin!

### ISSUE THREAD

**Issue by Atalkez** [svof/svof#777]
Paladin:

gmcp.Char.Vitals.charstats:
{ "Bleed: 0", "Rage: 0", "Wrath: 100.0%", "wrathbal: Yes", "Spec: Dual Cutting" }

Skills:

Valour - Chivalry reskin. No defs changed
Weaponmastery - No change
Excision: Uses Wrath (charstats[3]) and Wrath balance (charstats[4])

Fervour - PERFORM FERVOUR (gmcp FERVOUR)

Details:
When driven by divine fervour, any time someone in your room burns via
the ablaze affliction while also being afflicted with the pyre
affliction, you will be passively healed of an affliction. Additionally,
any time someone suffers from darkshade that you have afflicted them
with, the damage they will suffer from shall be more significant.

Dawnhand - PERFORM DAWNHAND (gmcp DAWNHAND)

Details:
The Lightbringer will guide your hand, bolstering your strength.

* Grants +1 strength.
** At dawn, grants +3 instead.

Faith - PERFORM FAITH (gmcp FAITH)

Details:
Your foes will come at you with sword and spell, but they will not avail
them: for you are clad not only in plate and chain but beneath the aegis
of your faith.

* Grants damage resistance to cutting, blunt, and magic damage. Less so
in the case of magic.

Retribution - PERFORM RETRIBUTION (gmcp RETRIBUTION)

Details:
By swearing to avenge any of your comrades(*) that fall in battle, any
time one of them is slain by an enemy of Creation(**), you will
immediately recover balance.

* Any member of Targossas or one of the Bloodsworn's orders.
** Anyone not from the above groups.

Unbowed - PERFORM UNBOWED (gmcp UNBOWED)

Details:
This defence will grant you a great surge of health when you enter a
drastically wounded state, similar to a monk's vitality. Notably
however, your faith is so strong that unlike a monk, this ability will
even save you from blows that would otherwise slay you(*).

* Excluding if the damage was unblockable.
*** There is a cooldown after this fires before you may raise the
defence again.

**Comment by tsartin** [comment]
@Atalkez Is it safe to assume all of these defenses use a physical balance to put up? Also is serverside able to put these defs up or do they need to be exclusively managed by svof?

Also besides the cooldown on unbowed is there anything weird that would keep these from being put up? Like perhaps being out of wrath? Thank you!

**Comment by Atalkez** [comment]
@tsartin 

These defenses require balance and equilibrium, and consume equilibrium to activate. Serverside is able to put them up, you just have to give it the gmcp defense that I listed above, eg: curing priority defense dawnhand 25. SVOF won't need to manage activation.

They do not require wrath to activate, so the only limitation is that cooldown on Unbowed.

**Comment by tsartin** [comment]
Any idea on the cooldown of unbowed? We have 2 minutes for vitality and I'd assume they're the same but want to make sure.

Does it also have the health/mana requirements like vitality?

**Comment by tsartin** [comment]
Sorry to ask so much, but do you also have the ingame lines for when these come on, off and when you check 'def'?

Do any of these drain mana?

Thanks!

**Comment by tsartin** [comment]
@Atalkez Any chance you'd be able to test these changes or perhaps know someone who can before we release it?

PS. for my question above. I just assumed unbowed was like vitality but if I am wrong let me know and I'll make those changes.
