### ISSUE TITLE
Possible Issue With svo.doadd

### ISSUE THREAD

**Issue by codeacula** [svof/svof#787]
I have a trigger set for `return isPrompt()` that runs the following code:

```lua
  if not Harmony.harvesting.harvestedRooms[mmp.currentroom] then
    for _, plant in ipairs(Harmony.harvesting.toHarvest) do
      svo.doadd("harvest " .. plant)
    end
  end
```

Before the most recent update, `svo.doadd` would execute immediately. Now, it requires an additional prompt to come in before it sends. This seems like a bug (as I would expect it to be instant), but I can't rule out user error just yet. I want to bring it up in case other people are noticing, though.

**Comment by TheLastDarkthorne** [comment]
Try to use 'prompt trigger' type instead of lua function to see if it works?

**Comment by codeacula** [comment]
@TheLastDarkthorne Tried, same result

![image](https://user-images.githubusercontent.com/5453902/197292864-3a1a5215-2fec-4401-b005-53a95d87b13a.png)

**Comment by tsartin** [comment]
@codeacula I loaded up a  new profile to test this and this is the results. It seems to have ran until I turned it off. It's mostly likely something that happened in your profile that's getting hung up. It very well could be an svo issue but it does not happen on a new profile so will need some more info to diagnose.

![image](https://user-images.githubusercontent.com/38020432/200360643-7957ecfa-f147-4d20-a716-788ab4a4eb08.png)


![image](https://user-images.githubusercontent.com/38020432/200360754-792e76e8-9298-40dc-962b-2fa818d93c9b.png)

**Comment by codeacula** [comment]
I forgot to come back and update this, my apolgies.

I realized this started happening because I changed the load order of different plugins. One of them now gets loaded after SVO, which means that it submits `svo.doadd` after the prompt has processed. I'll have to find a different way around it.

**Comment by vadi2** [comment]
Have a look at which events the system raises - you might be able to hook on one of them to queue your action at the right time.

**Comment by codeacula** [comment]
Thanks @vadi2, that was my plan, use the svo prompt event instead of a trigger
