### ISSUE TITLE
Do/Dofree/Dor commands delayed after addbalanceful with batching

### ISSUE THREAD

**Issue by keneanung** [svof/svof#79]
When using batching, the sending of dofree/do/dor (via expandAlias) is delayed until after the current batch, See https://github.com/svof/svof/blob/master/raw-svo.skeleton.lua#L741

If then things are added to the batch via sendc in svo.balanceful() to use up balance and thus cancel out dofree among other things.

**Comment by vadi2** [comment]
Without that queueing, expandAlias() won't work in dor, so taking it off might not be a good idea.

**Comment by keneanung** [comment]
Yeah, but the current solution is not ideal either. I have no better way yet, that's why I opened an issue how to best address this.

**Comment by vadi2** [comment]
Yep for certain. Batching isn't as trivial as it sounds, there are a couple
of edge cases like this that make it tricky.
