### ISSUE TITLE
undocumented luarocks dependency in generate.lua

### ISSUE THREAD

**Issue by bbailey** [svof/svof#8]
./generate.lua requires the luarocks loader but I see no additional dependencies on luarocks features.

Would it be a good idea to remove this to reduce dependencies? If it's just a quality of life issue of finding local lua library installations, similar results can be achieved by manipulating LUA_PATH/LUA_CPATH directly rather than relying on the luarocks loader to manipulate paths.

If we'd rather keep the loader, it would probably be a good idea to document the requirement in README.md

**Comment by vadi2** [comment]
Just add it to readme, removing it will make things more difficult to deal with.
