### ISSUE TITLE
Multiclass Support

### ISSUE THREAD

**Issue by alex-d-schroder** [svof/svof#81]
Now that multiclass is here, we need to be able to support it. Basically, this is how I see it working:

The system must be able to detect the current class the person is using.
The system must only use abilities granted for each class.
The system must be able to switch the defence screen to the currently used class.
The system must be able to remember user-defined defence lists for each class. (Preferably, the same alias (i.e. VDEFS BASIC) can be used for different classes and put up different defences. This could be done by keeping the general defence list the same between classes, and class specific defences stored with each class.)
The system must reset defences when the class is changed.
The system must recognize class change and adapt to it.

Most of all, this means that we're going to end up with only -one- release, one system to rule them all, that will work no matter what class the person is using. I have no idea how this will affect the final size of the system (though hopefully size will be reduced when we move afflictions and defences to gmcp).

This isn't an exhaustive list, and anything else that anyone can think of should be posted here so we can make sure we're working on it.

**Comment by QwindorRousseau** [comment]
Your current class xan already be seen through gmcp via gmcp.Char.Status.class . But yes once afflictions are made to use gmcp instead of a ton of triggers this will reduce the size of it immensly and should also speed up the system itself as well.

**Comment by QwindorRousseau** [comment]
Easiest thing i could see would be importing the jist the class defense portions and start on that for it to disable and enable the other classes via the gmcp change

**Comment by vadi2** [comment]
Here are my thoughts on this - how you guys want to implement it is up to you.

Adding multiclass support is made much easier by the class that a class Svof is basically a bunch of skillsets. So for a multiclass system, you'd build a Svof with all skillsets included, and that's as trivial as adding a new class with all skillsets in classlist (see [m&mf](https://github.com/m-mf/m-mf/blob/master/classlist.lua#L30)). 

Once you've got all skillsets in one, part two is showing and using the right ones. Showing the right skillsets on defence lists is facilitated by the fact that Svof's defence database knows which skill comes from which skillset ([see type](https://github.com/svof/svof/blob/master/raw-svo.defs.lua#L516)) and the fact that a hidelist feature allows you to toggle which skills or even skillsets should be visible. So using hidelist to toggle which skillsets should be shown is easy, the harder bit would be obeying the users own preferences for which things should be shown.

Using the right skills from skillsets you've got is a similar deal - as Svof knows which defence, thus which action, comes from which skillset, you can just put in a check into the [check_* functions](https://github.com/svof/svof/blob/master/raw-svo.skeleton.lua#L538) that looks up the skill - checks if it's a defence, and if it is one, part of the skillsets the current class you're on has active - and just returns a boolean if it's a defence you can or can't do. I'd recommend having this check before isadvisable call for optimisation reasons.

That's about it at a high level. I wouldn't recommend resetting defences, storing defences separately per class, or even making the user switch defences to the class they're using. It can all be very dynamic without their involvement and with minimal impact on their understanding on how to use the system - basically, "just work".

You'd also want to implement this reasonably quickly, people want stuff sooner than later.

**Comment by keneanung** [comment]
The following diff is what I did to get a combined runewarden and monk svof. It will show the defenses of both classes at once, shared defenses only in one section. And of course it does not use the correct defense modes automatically. I created a "runie" one to switch to when becoming runewarden.

~~~~~

diff --git a/generate.lua b/generate.lua
index 4324044..c683c84 100644
--- a/generate.lua
+++ b/generate.lua
@@ -25,7 +25,7 @@ local args = lapp [[
 -d,--debug  Build with debugging information enabled
 -r,--release (default false)  Build all systems
 -o,--own  Build a Svof for yourself
- <name...> (default infernal )  Class to build a system for
+ <name...> (default none )  Class to build a system for
 ]]
 
 --[[
@@ -33,7 +33,8 @@ local args = lapp [[
 ]]
 
 local builder         = "lua" -- or "luajit"
-local doall           = args.release ~= "false" -- make doall a bool
+local doall           = args.release ~= "false" and args.name == "none" -- make doall a bool
+print("doall is " .. (doall and "true" or "false"))
 local name            = args.name
 local release         = not args.debug
 local own             = args.own
@@ -102,13 +103,13 @@ local function dowork(systemfor, release, own)
   tbl.pairs = pairs
   tbl.table = table
   tbl.type = type
-  tbl.tostring = tostring
+  tbl.tostring = tostring00
   tbl.require = require
   tbl.package = package
   tbl.print = print
   tbl.pcall = pcall
   tbl.skills = {}
-  tbl.class = systemfor
+  tbl.class = stringx.split(systemfor, " & ")
   tbl.io = io
 
   if not tbl.class then
@@ -131,7 +132,7 @@ local function dowork(systemfor, release, own)
 
   -- add default addons
   for k, addon in pairs(defaultaddons) do
-    if type(k) == 'number' or k == tbl.class then
+    if type(k) == 'number' or tablex.find(tablex.values(tbl.class), k) then
       if type(addon) == "string" and not tablex.find(tbl.addons, addon) then
       tbl.addons[#tbl.addons+1] = addon
       elseif type(addon) == "table" then
~~~~

**Comment by vadi2** [comment]
Don't go the way of building several classes in one - just make a new class (allclasses) that has all skillsets in it. No generate.lua modiifcation necessary then.

**Comment by keneanung** [comment]
Allclasses will also need to have all plugins, which currently doesn't work, because main has more than 200 locals and at least magi, monk and meta limbcounter have naming conflicts

**Comment by vadi2** [comment]
I'd update the addons then to move the locals into tables. As for the namespace conflicts - that would be a bit of work, but it should be possible to dynamically load the right functions in. As a first pass, I wouldn't include the conflicting plugins - release multiclass first and then solve that.

**Comment by keneanung** [comment]
We will also need to amend preprocessor directives that look for certain classes like `#if class == "druid"`

**Comment by vadi2** [comment]
I'm adding 100 bounty credits to this.

**Comment by QwindorRousseau** [comment]
Umm I think this will be another one that we can close out with the version we are currently all working on.
