### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by lisbethae** [svof/svof#82]
*write or write used to open up an editor window for me, until yesterday 9/27/2015.

This morning it does not. 

Is there a setting I need to tweak or is this a bug? Who works on these things?

**Comment by pathurs** [comment]
What is this in reference to? Do you mean the mudlet text editor for news, letters, journals etc?

If so that's a mudlet issue I believe, not SVOF

**Comment by Datyriam** [comment]
this'll be a mudlet issue, yes, similar with how mudlet does not recognise the leaving of the leadership editor window

**Comment by keneanung** [comment]
@lisbethae Is this still an issue? As others commentators said, the editor is a mudlet feature and nothing that's controlled by svof.

Why do you think it's related to svof?

**Comment by jgh713** [comment]
Probably best to go ahead and close this for now.
