### ISSUE TITLE
Endless Loop Honors-ing Fayad

### ISSUE THREAD

**Issue by lmclarke** [svof/svof#826]
![image](https://user-images.githubusercontent.com/3780592/236995269-ec99a73b-df50-4286-b4ce-4f7f1c5bda66.png)

Just keeps doing this infintiely for anyone with the third gender option set on themselves.

**Comment by MediaResAchaea** [comment]
@lmclarke - It's definitely something more complicated than what you've described, honors'ing people with the Fae pronoun works just fine and I can't repro this. I've never had this infinitely loop before, but I have had it honors someone multiple times if I'm trying to honors in the middle of doing things that take balance. 

You can cancel an ongoing lookup with ndb cancel, is this consistently reproducible for you?

**Comment by lmclarke** [comment]
It is reproducable for me, yep yep (and thank you for the heads up on ndb cancel - that's hugely handy to know). I've only see two people thus far with the Fae gender and it does it on both of them (Lif, Bunni). 

Edit: Update - does it on Sheena as well, who has the Fae gender.

**Comment by lmclarke** [comment]
Sorry for the double post, this seems to be a version issue. I grabbed the latest from releases without paying enough attention and missed the up to date in-client version. Definite PEBKAC, closing this.
