### ISSUE TITLE
vversion bug

### ISSUE THREAD

**Issue by Datyriam** [svof/svof#93]
using VVERSION returns the correct svo version, but also runs the old svo code to check for updates (which prompts you to update to SVO 15.8.1) - may want to disable this or reroute it to check the github releases somehow

**Comment by gymosphere** [comment]
We could redirect autoupdate to a non-https mirror, I am trying to setup a server now, and pass it to @keneanung for further action.

**Comment by keneanung** [comment]
Will be fixed with next release.
