### ISSUE TITLE
Water weird collapse is not removing waterweird defence (Magi)

### ISSUE THREAD

**Issue by seriley** [svof/svof#97]
A trigger on the following pattern needs to reset svo.defc.waterweird to false (probably after checking that it's the player's water weird):

The water weird suddenly collapses into a puddle of normal water.

As it stands now, the flag remains true until the 'def' command is executed

**Comment by keneanung** [comment]
This could probably be fixest with #44

**Comment by jgh713** [comment]
Waterweird doesn't add or remove a gmcp defence, There's a gmcp def for waterwalking, I'm assuming it's the blademaster skill.

**Comment by jgh713** [comment]
Best way to do this is probably capture which waterweird is added to gmcp room data on summon, then remove the def when that weird is removed.

**Comment by QwindorRousseau** [comment]
This is an old issue that might have been fixed in one of the past updates. Going to close for now but feel free to test on the in-client and reopen it and then we can look into what we can do but it will not be a major factor for getting a beta going or the official release.
